### ISSUE TITLE
Project.EnabledModuleNames is empty 

### ISSUE THREAD

**Issue by ANovitsky** [zapadi/redmine-net-api#101]

**Comment by MyLittleDev** [comment]
I had the same issue, you just have to create this class
  [XmlRoot("enabled_module")]
    public class ProjectEnabledModule : IdentifiableName, IEquatable<ProjectEnabledModule>
    {
        public bool Equals(ProjectEnabledModule other)
        {
            if (other == null) return false;
            return Id == other.Id && Name == other.Name;
        }

        public override string ToString()
        {
            return Id + ", " + Name;
        }
    }
Add this to Project Class
        [XmlArray("enabled_modules")]
        [XmlArrayItem("enabled_module")]
        public IList<ProjectEnabledModule> EnabledModules { get; set; }

And this to ReadXml method
                    case "enabled_modules": EnabledModules = reader.ReadElementContentAsCollection<ProjectEnabledModule>(); break;

Only work for read, don't touch the right because don't need ;)
Hope this help
