### ISSUE TITLE
RedmineManager.UpdateObject does not work

### ISSUE THREAD

**Issue by Maaarek** [zapadi/redmine-net-api#104]
I get always the Error "Not Found", if I am traying to Update on Object.
![unbenannt](https://cloud.githubusercontent.com/assets/14011754/9578526/fb8348da-4fea-11e5-847b-ece1ea230b05.jpg)
It works if i use GetTotalObjectList but get alaways a error when I try to use UpdateObject .
What could be the reason ? I

thx

**Comment by zapadi** [comment]
You should get the issue first (based on ticket.Id) and then to update the fields.
Check the wiki page for update - https://github.com/zapadi/redmine-net-api/wiki/Update-a-redmine-object

**Comment by Maaarek** [comment]
I tried that before. It can not find one specific issue but the Methode GetTotalObjectList works.
![unbenannt](https://cloud.githubusercontent.com/assets/14011754/9596802/3f78d638-507a-11e5-8375-8b8978c28461.png)

**Comment by zapadi** [comment]
Could you show me the result that you get by GetTotalObjectList for the issue with id = 11114 ?

**Comment by Maaarek** [comment]
I mean that I get all issue´s with the GetTotalObjectList. 
![unbenannt](https://cloud.githubusercontent.com/assets/14011754/9602395/6a3a6e08-50a8-11e5-9a7e-b250397a313e.png) 
That is an other issus but that is not important at this point. I have the propblem with every issue.
I used to the second UpdateObject() but it does not work.

**Comment by zapadi** [comment]
ok! try this in the web browser and let me know if it works
http://<your redmine address>/issues/11114.xml?key=<your api key>

**Comment by Maaarek** [comment]
I get:
Page not found 
The page you were trying to access does not exist or has been removed.

That very curious.

**Comment by zapadi** [comment]
Now try the same thing with the id = 11121.

**Comment by Maaarek** [comment]
The same problem.

**Comment by Maaarek** [comment]
Do you have any idea what could be the reason for this dilemma ?

**Comment by zapadi** [comment]
open in web browser an issue and check the url. In my case is like this http://&lt;redmine address&gt;/issues/18

**Comment by Maaarek** [comment]
Gotcha. He founds the issue "GetObject" only the Methode UpdateObject do not works. But it is a progress. I change the url, when I called the issue with GetObject.

**Comment by Maaarek** [comment]
I find the mistake It works well when I change the Description but it does not change the value AssignetTo.Name or Author in the issue. Could be that I can not change this properties ?

**Comment by zapadi** [comment]
I'll check it.

**Comment by Maaarek** [comment]
thanks

**Comment by zapadi** [comment]
you're welcome
