### ISSUE TITLE
NotFound IssuePriority

### ISSUE THREAD

**Issue by Maaarek** [zapadi/redmine-net-api#110]
Hallo,
I am trying to call the IssuePriority of the specific project. What could be the problem that it can't find the values.

![error](https://cloud.githubusercontent.com/assets/14011754/9755751/dc827f6e-56d4-11e5-9956-6547d176905d.jpg)

**Comment by zapadi** [comment]
Based on redmine api docs you can't get a list of issue priorities for a specific project (http://www.redmine.org/projects/redmine/wiki/Rest_Enumerations) but you can get all the issue priorities that are defined.

**Comment by Maaarek** [comment]
I hope it's ok for you when I contect you about the e mail.
Thanks , I get without a Problem all Statues Values. I have not idea how to
get all issue priorities. How has to look like the methode to get all issue
priorites. That what I tried does not work.

2015-09-09 10:36 GMT+02:00 Padi <notifications@github.com>:
