### ISSUE TITLE
journals of issue is null

### ISSUE THREAD

**Issue by phdelodder** [zapadi/redmine-net-api#111]
When I use the following code: 

Issue journalIssue = redmineManager.GetObject<Issue>(issue.Id.ToString(), new NameValueCollection { { "include", "journals" } });

The journals is always null, is this an issue?

When I use an other rest client I can get the journals info. So It would be nice to have journals filled in.

**Comment by zapadi** [comment]
I'm not able to reproduce the error. Could you give me more details about it(redmine.api version, MimeType=xml/json, etc)?

**Comment by phdelodder** [comment]
i'm using redmine net api 0.10.0 from nuget

I don't know how to specify the mime type. 

The example code I use:

RedmineManager redmineManager = new RedmineManager("https://Location/",
               WebConfigurationManager.AppSettings["RedmineApiKey"]);

            var parameters = new NameValueCollection { { "status_id", "open" } };

            IList<Ticket> tickets = new List<Ticket>();

            foreach (Issue issue in redmineManager.GetTotalObjectList<Issue>(parameters))
            {
                if (!issue.Status.Name.Equals("Feedback"))
                    continue;

                Issue journalIssue = redmineManager.GetObject<Issue>(issue.Id.ToString(), new NameValueCollection { { "include", "journals" } });

                if (journalIssue.Journals == null)
                    continue;

                foreach(Journal journal in journalIssue.Journals)
                {
                    if (journal.CreatedOn.Equals(issue.UpdatedOn) && journal.User.Id != 85)
                    {
                        tickets.Add(parseTicket(issue));
                    }
                }
            }

**Comment by zapadi** [comment]
Please use the last version available on nuget (0.14). The mime type can be set in redmine manager constructor.

**Comment by phdelodder** [comment]
With the 0.14 it works
