### ISSUE TITLE
Get all Attributes of FixedVersion

### ISSUE THREAD

**Issue by Maaarek** [zapadi/redmine-net-api#113]
It's possible to get all Attributes of FixedVersion of a RedmineProject ??

**Comment by zapadi** [comment]
Attributes of fixed versions?

**Comment by Maaarek** [comment]
It's exist in the class "issue.FixedVersion.Name" but that only one of possible Version what is include in the project. I want all possible FixedVersion of a Project.

**Comment by zapadi** [comment]
I'm afraid that is not possible.

**Comment by Maaarek** [comment]
ok thx zapadi I have already opened an other issue ^^ If you have a free minute
