### ISSUE TITLE
Update Redmine Object

### ISSUE THREAD

**Issue by Maaarek** [zapadi/redmine-net-api#114]
In Wiki the example to upload a issue.object works well if you want to change the description but it doesn't work when I try to change the Priority or the status. 
Could it be that the upload methode works only for the description ?

**Comment by zapadi** [comment]
Let me do some tests and I'll let you know

**Comment by Maaarek** [comment]
Thanks you very much.

**Comment by Maaarek** [comment]
It works. 
The property Description doesn't have a ID. If you to change a value in Priority it workds only if you change the ID.
