### ISSUE TITLE
Unable to get Custom Field values

### ISSUE THREAD

**Issue by nowagner** [zapadi/redmine-net-api#116]
I am attempting to use the redmine-net-api to pull all of the values for a specific custom field from Redmine.  I have tried the below suggestions from other issues I've found with a google search and nothing seems to work.  

When I get the Project object the CustomFields collection is null.  When I get an Issue the selected value of the Custom Field is populated but I can't get all possible values.  When I try to query for the Custom Field itself I get a "Not Found" exception.

Could you tell me the correct way to get a Custom Field from Redmine using the API?  According to the REST API documentation this should be possible.

var project = manager.GetObject<Project>("1", new NameValueCollection() { { "include", "CustomFields" } });

var issue = manager.GetObject<Issue>("17549", new NameValueCollection() {{"include", "custom_fields"}});

var custField = manager.GetObject<CustomField>("1", new NameValueCollection() { { "Name",  Requested Department" } });

**Comment by zapadi** [comment]
Try this 
var projects = redmineManager.GetObject<Project>("1", new NameValueCollection(){{"include","custom_fields"}});

**Comment by nowagner** [comment]
Sorry, I should have mentioned that in my original comment, I did try that as well.

As you can see in the image I (hopefully) attached the CustomFields collection is null, even though I specify to include custom fields.

![image](https://cloud.githubusercontent.com/assets/14279997/9882925/40df60b0-5ba5-11e5-83ce-466edb2e600b.png)

**Comment by zapadi** [comment]
What is the version of the redmine-api that you are using?

**Comment by nowagner** [comment]
Here you go:

Environment:
Redmine version 2.5.0.stable
Ruby version 1.8.7-p358 (2012-02-08) [x86_64-linux]
Rails version 3.2.17
Environment production
Database adapter MySQL

SCM:
Subversion 1.6.11
Git 1.7.1
Filesystem 

Redmine plugins:
no plugin installed

**Comment by zapadi** [comment]
are you using the latest version of the redmine-api from nuget (0.14) or is it an older one?

**Comment by nowagner** [comment]
yes, I am using the latest version from nuget, 0.14

Could this have anything to do with the setup in Redmine?  I am using an API key to access, and the user that generated the API key is set up as an administrator so that I can do user impersonation.

**Comment by nowagner** [comment]
I did confirm that if I call the REST API directly with the following I get the custom field definition.  Is this possible with the redmine-api?  The response I receive gives me all the information I'm looking for (definition, possible values, etc.)

GET /custom_fields.xml

**Comment by nowagner** [comment]
I figured it out, the following code worked, passing an empty NameValueCollection was the key.

var allcustfields = manager.GetObjectList<CustomField>(new NameValueCollection());

Thanks for your help!

**Comment by zapadi** [comment]
you're welcome.
