### ISSUE TITLE
Calling Problem

### ISSUE THREAD

**Issue by Maaarek** [zapadi/redmine-net-api#117]
Hallo,
I have little problem.
Right now, I can register with my account after that I would like call only all my Project who I am register.
In the last step, I can pick one of the project and call all issuse what are include in that project. 
Is that possible ? 
I am thanks full for every solution.

regards Maarek

**Comment by zapadi** [comment]
It is possible. You have tot call for a specific project GetTotalObjectList&lt;Issue&gt;(null) and you will get all the issues. If you need to filter the issues you can pass your filter instead of null.
