### ISSUE TITLE
Xml serialization is broken - cannot create issue

### ISSUE THREAD

**Issue by fnajera-rac-de** [zapadi/redmine-net-api#119]
Hi,

I'm not 100% sure of this being a bug of the library, but I think it is.

Using d1c7ebb, the following code:

    var newIssue = new Issue
                    {
                        Subject = ...,
                        Description = ...,
                        Project = new IdentifiableName { Id = ... },
                        Priority = new IdentifiableName { Id = ... },
                        CustomFields = new List<IssueCustomField> { ... },
                        Uploads = new List<Upload>
                        {
                                fileUpload
                        }
                    };

Produces the following xml:

    <issue>
        <subject>...</subject>
        <notes />
        <description>...</description>
        <is_private>False</is_private>
        <project_id>...</project_id>
        <priority_id>...</priority_id>
        <estimated_hours />
        <done_ratio />
        <start_date />
        <due_date />
        <updated_on />
        <uploads type="array">...</uploads>
        <custom_fields type="array">...</custom_fields>
    </issue>

In particular, I think the problem is on the "`<done_ratio />`" empty element.

Redmine chokes with this XML giving out: 422, "% Done is not included in the list"

Exactly the same code using json works without error.

**Comment by fnajera-rac-de** [comment]
I am almost certain that the issue was introduced at 1f0d9375e6d7 - before that, the tag was written only if it had a value, and after that, it's always written, even empty.

**Comment by zapadi** [comment]
This issue is solved in dev brach. I'll merge them soon.
