### ISSUE TITLE
Limited MaxJsonLength

### ISSUE THREAD

**Issue by ANovitsky** [zapadi/redmine-net-api#123]
Limited MaxJsonLength, please set:

var ser = new JavaScriptSerializer()
            {
                MaxJsonLength = int.MaxValue
            };

System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   bei System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(String input)
   bei Redmine.Net.Api.RedmineSerialization.JsonDeserializeToList(String jsonString, String root, Type type, ref Int32 totalCount)
   bei Redmine.Net.Api.RedmineSerialization.JsonDeserializeToList(String jsonString, String root, ref Int32 totalCount)
   bei Redmine.Net.Api.RedmineManager.DeserializeList(String response, String jsonRoot, ref Int32 totalCount)
   bei Redmine.Net.Api.RedmineManager.ExecuteDownloadList(String address, String methodName, String jsonRoot, ref Int32 totalCount, NameValueCollection parameters)
   bei Redmine.Net.Api.RedmineManager.GetObjectList(NameValueCollection parameters, ref Int32 totalCount)
   bei Redmine.Net.Api.RedmineManager.GetTotalObjectList(NameValueCollection parameters)

**Comment by zapadi** [comment]
Done.
