### ISSUE TITLE
Share some methods to virtual

### ISSUE THREAD

**Issue by ANovitsky** [zapadi/redmine-net-api#124]
Hello, 

Could you create virtual methods?, because I want to add some app logging and other.. but I can't..

Methods for virtual:
bool RemoteCertValidate - if I need false,
private void HandleWebException - I need provide custom errors

I need add app logs like a [GET] {URL}?{PARAMS}, please set virtual for:

private IList<T> ExecuteDownloadList<T> 
private T ExecuteDownload<T>
private T ExecuteUpload<T>
private void ExecuteUpload

Why you hiding everything? Because of this, I have to do brunch. Make a some code, rebuild, retest..

Please :)

**Comment by zapadi** [comment]
Hello,

I will implement the required changes.

:)
