### ISSUE TITLE
% Done is not included in the list

### ISSUE THREAD

**Issue by ANovitsky** [zapadi/redmine-net-api#126]
{"issue":{"subject":"Test Taskzdmct5ab.g1k71557968-980e-4e1a-b4e6-2ddf02d7b21d","description":null,"notes":null,"is_private":false,"project_id":1387,"priority_id":2,"status_id":1,"tracker_id":1,"estimated_hours":"","parent_issue_id":null,"start_date":"","due_date":"","updated_on":"","done_ratio":""}}

done_ratio is empty? but should be '0'

**Comment by zapadi** [comment]
Solved.
