### ISSUE TITLE
API returns an Issue without relational infomation by default

### ISSUE THREAD

**Issue by jhmt** [zapadi/redmine-net-api#127]
Hi zapadi, Thank you publishing this great library. I love to use this.

This is an enhancement suggestion.

According to this page: http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Showing-an-issue

Redmine API returns an Issue without any relational infomation such as children and attachmens unless **include** parameters are specified. However, I think .NET developers need those additional information in most cases.

Although it might be a trade-off between convenience and overhead, I would like to make it easier to get the infomation as necessary.

My idea is to pass **include** parameters with using bit flags.

**Comment by zapadi** [comment]
Thank you for your kind words.

What about the other types that have include parameters(project,group, etc)?

I want to keep this library as generic as it can be.

Adrian Popescu

On 28 Oct 2015, at 23:19, Jun Hashimoto <notifications@github.com> wrote:

Hi zapadi, Thank you publishing this great library. I love to use this.

According to this page:
http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Showing-an-issue

Redmine API returns an Issue without any relational infomation such as
children and attachmens unless *include* parameters are specified. However,
I think .NET developers need those additional information in most cases.

Although it might be a trade-off between convenience and overhead, I would
like to make it easier to get the infomation as necessary.

My idea is to pass *include* parameters with using bit flags.

—
Reply to this email directly or view it on GitHub
<https://github.com/zapadi/redmine-net-api/issues/127>.

**Comment by jhmt** [comment]
Hi Adrian,

Thank you for your prompt reply.

It would be helpful for me to have include parameter options for other types. (project,group, etc).
However, they should make this library less generic so I'll close this issue and my pull request related this.

Thanks anyway.
