### ISSUE TITLE
Is_Private Processing

### ISSUE THREAD

**Issue by portilha** [zapadi/redmine-net-api#130]
Hello, I have been using Redmine REST C# Api and i found that the is_private is being exported with the value "True" or "False", values that the redmine does not process (at least at version 2.4.1), I had to change the following line in the Issue.cs file so the redmine would accept the value,

writer.WriteValue(IsPrivate.ToString().ToLowerInvariant());

Thanks,

**Comment by zapadi** [comment]
Thank you.
