### ISSUE TITLE
Little bug in tests

### ISSUE THREAD

**Issue by radeczek** [zapadi/redmine-net-api#133]
Hi,
I have found little bug in tests - redmine-net-api/UnitTestRedmineNetApi/IssueTests.cs 
Line: 189 - Assert.AreEqual(issue.Subject, issue.Subject);
Probably should be Assert.AreEqual(issue.Subject, updatedIssue.Subject);

Its probably typo mystake.
Thank you for your APi implementation.
Rcz

**Comment by zapadi** [comment]
Thank you for pointing that out.
