### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by dfch** [zapadi/redmine-net-api#134]
Hi, we are using your .NET library to work with the RedMine API. Thanks for that!

We found an error when using the NuGet package. The current binaries in the `v0.10.0` have a bug regarding attachment uploads. However, fortunately this is already fixed in the master branch (but not yet released to NuGet).

Could you please update the NuGet package or would you mind if we released an updated NuGet package (under a new name)?

Thanks for your reply!
Regards, Ronald

**Comment by zapadi** [comment]
Hi Ronald,

That version was not released by me :). 

Here you can find the latest one and in January I'll add a new version of NuGet package.

Regrads,
Padi

**Comment by dfch** [comment]
cool and thanks for the quick reply! in the meantime we will add the library directly to our project

and again thanks for the library - saved us a lot of time and effort! Ronald
