### ISSUE TITLE
Private notes in Issues not correcty serialized to JSON

### ISSUE THREAD

**Issue by afcaJordi** [zapadi/redmine-net-api#135]
Hello, I have found a Bug in serializing Redmine-Issues to JSON: For the key PRIVATE_NOTES the value IsPrivate is used. I think it should be PrivateNotes.
See Redmine.Net.Api.JSonConverters.IssueConverter line 83.

**Comment by dfch** [comment]
@afcaJordi if it is a small code change, could you fix this and create a pull request for @zapadi ? he mentioned he would release an updated nuget package in January. Until then we will have these changes in our local copy and use the official package afterwards (along with the other fixes).
