### ISSUE TITLE
Does the redmine component work with proxy server?

### ISSUE THREAD

**Issue by ilyakoshevoi** [zapadi/redmine-net-api#145]
Hi, I would like to know if a client has internet access via proxy server how it should be handled?
Currently (by default) when I request an issue by number the component immediately returns 'null' despite the issue exists. There are no exceptions!

All what I need is to specify "use system proxy from IE settings".

**Comment by betler** [comment]
Same happens to me. Everything comes as null.

**Comment by betler** [comment]
I modified RedmineManager.cs (redmine-net45-api). This works for me, although, is necessary to ask for credentials before:

```
        public virtual RedmineWebClient CreateWebClient(NameValueCollection parameters, bool uploadFile = false)
        {
            var webClient = new RedmineWebClient();

            // Added by betler 20160219
            IWebProxy webProxy = WebRequest.GetSystemWebProxy();
            if (webProxy != null)
            {
                // Proxy should be used
                webClient.UseProxy = true;
                NetworkCredential creds = new NetworkCredential(user, password);
                webProxy.Credentials = creds;
                webClient.Proxy = webProxy;
            }
            // Added by betler 20160219
            [...]
```

**Comment by zapadi** [comment]
Now RedmineManager handles proxies.
