### ISSUE TITLE
(500) Internal Server Error on create Issue

### ISSUE THREAD

**Issue by BLACKSnake-rus** [zapadi/redmine-net-api#149]
Hi, I using redmine-net45-api.dll version="1.0.1"
I tried use this code:
```
redMineManager = new RedmineManager(redMineUri, redMineLogin, redMinePassword);
var a = redMineManager.GetObject<Issue>("61119", new NameValueCollection()) as Issue;
var newIssue = new Issue
{
    Subject = a.Subject,
    Description = a.Description,
    Project = new IdentifiableName() { Id = a.Project.Id },
    Tracker = new IdentifiableName() { Id = a.Tracker.Id },
    Status = new IdentifiableName() { Id = a.Status.Id },
    Priority = new IdentifiableName() { Id = a.Priority.Id },
    AssignedTo = new IdentifiableName() { Id = a.AssignedTo.Id },
    IsPrivate = a.IsPrivate
};
redMineManager.CreateObject(newIssue);
```
Results:
```
Internal Server Error
```

**Comment by BLACKSnake-rus** [comment]
This problem is solved in this repository. Please update the version on NuGet.org

**Comment by dbeilloi** [comment]
Hi,
same problem, would be really nice to get a new nuget package !

**Comment by zapadi** [comment]
Hi,

Next week the new nuget package will be available to download.

Adrian

On 08 Mar 2016, at 23:52, dbeilloi <notifications@github.com> wrote:

Hi,
same problem, would be really nice to get a new nuget package !

—
Reply to this email directly or view it on GitHub
<https://github.com/zapadi/redmine-net-api/issues/149#issuecomment-194005096>
.

**Comment by BLACKSnake-rus** [comment]
Thank you. 
Will wait

**Comment by dbeilloi** [comment]
great, thanks!
