### ISSUE TITLE
GetObject<Issue> parameters not applied

### ISSUE THREAD

**Issue by toddams** [zapadi/redmine-net-api#151]
I have a code:
```
var parameters = new NameValueCollection { { "include", "journals" } };
var issue = Manager.GetObject<Issue>(selectedObject.Id.ToString(), parameters);
```

But I got null Notes at response. Then I watched a request using Fiddler and I noticed, that parameters were not applied:

GET http://test.example.net/issues/4541.xml?key=f23bda80ergerr07820d9ewf886da HTTP/1.1
Content-Type: application/xml; charset=utf-8
Host: test.example.net
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

As you can see "Include" is not in request

**Comment by zapadi** [comment]
This is the normal behaviour. you have requested "journals".

**Comment by toddams** [comment]
Look at the GET request, there is no &include=journals at all, that means that parameters were not applied at all, no matter what I requested
