### ISSUE TITLE
CreateObject<Issue> has invalid or missing attribute parameters: Project cannot be blank

### ISSUE THREAD

**Issue by camous** [zapadi/redmine-net-api#155]
I'm getting trouble creating a new issue
either in form
`redmine.CreateObject<Issue>(new Issue { Subject = table.Name, Project = new IdentifiableName() { Id = 1 }, Tracker = new IdentifiableName() { Id = 1 }, Status = new IdentifiableName() { Id = 1 } });`
or
`                        Issue issue = new Issue();
                        issue.Project = new IdentifiableName() { Id = 2 };
                        issue.Subject = table.Name;
                        issue.Status = new IdentifiableName() { Id = 3 };
                        redmine.CreateObject(issue);`

Project id = 1 exists
![image](https://cloud.githubusercontent.com/assets/8566299/14811954/2cb0e5a4-0b9b-11e6-86c7-55bd4d852e6c.png)

and here the feedly trace
![image](https://cloud.githubusercontent.com/assets/8566299/14812069/bcfa33f4-0b9b-11e6-8e1c-f4f1b5453895.png)

response
![image](https://cloud.githubusercontent.com/assets/8566299/14812072/bed5b004-0b9b-11e6-8f87-873995f4f6a9.png)

is it a redmine bug ?

environment
* Redmine version                3.2.0.stable
*  redmine-net-api 0.1.1.0 (from nugget)

**Comment by camous** [comment]
after further "random" investigation, I found the root cause.
on my docker redmine sandbox, for the newly created project, no trackers were "activated"
![image](https://cloud.githubusercontent.com/assets/8566299/14835146/93b12616-0c08-11e6-9a99-314331ee5820.png)

activating them fixed my issue. I assume the error message from redmine is misleading. I will create a ticket on redmine.org (maybe it could help)

**Comment by zapadi** [comment]
Thank you. I'll update the documentation in order to point out this issue.
