### ISSUE TITLE
Create Issue with CustomField

### ISSUE THREAD

**Issue by josemigueldel85** [zapadi/redmine-net-api#156]
Hello, i have a question.
How do i create an issue with a customfield, do you have an example.

`IssueCustomField usuario = new IssueCustomField();
                    usuario.Id = 5;
                    usuario.Name = "Solicitante";
                    CustomFieldValue valor = new CustomFieldValue();
                    valor.Info = solicitante;
                    usuario.Values.Add(valor);`

I tried in this ways, but doesnt works.

**Comment by josemigueldel85** [comment]
I found an working example.

`Issue issue = new Issue
                    {
                        Project = new IdentifiableName() { Id = PROYECTO }, //Proyecto
                        Priority = new IdentifiableName() { Id = 3 }, //Prioridad Alta
                        Subject = asunto,
                        Description = descripcion,
                        Category = new IdentifiableName() { Id = 9 }, //Categoria desarrollo gráfico
                        Status = new IdentifiableName() { Id = 1 },   //Estado nueva
                        AssignedTo = new IdentifiableName() { Id = USUARIO },  //Asignación*/
                        CustomFields = new List<IssueCustomField>
                        {
                            new IssueCustomField
                            {
                                Id = 13,
                                Values = new List<CustomFieldValue> {new CustomFieldValue {Info = solicitante}}
                            }
                        }           
                    };`

**Comment by jbolonski** [comment]
Below is code that I use to create a custom field.

`var customField = new IssueCustomField()
{
	Id = 5,
	Name = "FieldName",
	Values = new List<CustomFieldValue>()
};

customField.Values.Add( new CustomFieldValue() { Info = "Value to add"} );

issue.CustomFields.Add(customField);
`
