### ISSUE TITLE
http error 406

### ISSUE THREAD

**Issue by bubibubi** [zapadi/redmine-net-api#164]
I'm trying to run an example as simple as this
http://www.redmine.org/projects/redmine/wiki/Rest_api_with_csharp

I'm using an apikey (with user/password the problem is the same) and I'm using my redmine server with 3rd parties app that uses webapi (so Redmine should work properly).

About the url that I'm passing to the manager it is in the form http://myurl/

I had a look with wireshark and the Redmine server answer to the library with the following response:
406 - Client browser does not accept the MIME type of the requested page
The page you are looking for cannot be opened by your browser because it has a file name extension that your browser does not accept.

**Comment by bubibubi** [comment]
A step forward:
the issue arises if there is an error in the request (i.e. a wrong project id).
Actually I don't know if it's a Redmine issue (every API exception generates a 406 issue) or if it is RedmineWebClient not properly configured to accept the error response from RedMine.

**Comment by bubibubi** [comment]
Last step:
after solving another problem I could add an Issue to redmine.
The issue is added to redmine but I still receive the answer 406.
I'm using redmine 2.3-stable

**Comment by gfrSE** [comment]
Using Redmine 3.1.2.stable.14192.
I am trying to read the issues (async) like the example in your wiki..

Only getting error 406!

Web API Service is enabled.
If i am enter a wrong authentication-pass it throws an error with "wrong login" ..
So communication seems fine.

Whats else could be wrong?
Thanks.

**Comment by gfrSE** [comment]
Redmine error message:

// first i was trying to read the issues ..

ActionController::UnknownFormat (ActionController::UnknownFormat):
  app/controllers/issues_controller.rb:76:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

// i tried the projects too..

ActionController::UnknownFormat (ActionController::UnknownFormat):
  app/controllers/projects_controller.rb:46:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by bubibubi** [comment]
Just to understand if RedMine works fine you can install an application that access to RedMine via WebAPI. I'm using RedminePM on Android.

**Comment by gfrSE** [comment]
Thanks for that tip!

Redmine is working fine with this app!

**Comment by bubibubi** [comment]
Ok, found my problem (probably related to installing RedMine on Windows or my RedMine version).
The extension of the requested api has the first letter capitalized (for example issues.Json).
This is the problem.
Changing the extension to json everything works fine.
I think that in your case, after fixing the library (you have to change MimeFormat enum because the extension is the enum ToString) you will receive an error in a JSON envelope.

**Comment by gfrSE** [comment]
Great, thanks!
Same solution works here!
I am on Windows too.

**Comment by zapadi** [comment]
Thank you for pointing it out. I'll fix it asap.
