### ISSUE TITLE
support for .net core

### ISSUE THREAD

**Issue by neridonk** [zapadi/redmine-net-api#167]
I want to use this libary in my asp.net Core 1.0 app please make it possible

**Comment by Deilan** [comment]
Definitely would like to see that happen.

**Comment by zapadi** [comment]
It's happening! :)
You can check the progress at https://github.com/zapadi/redmine-netcore-api/tree/dev.

**Comment by Deilan** [comment]
I'd say it should not be closed before the complete migration to the .NET Core version. Moreover, there is still no even a NuGet package for .NET Core version.

**Comment by zapadi** [comment]
I agree with you.

**Comment by lferrao** [comment]
Hi @zapadi, is it normal that I don't see GetPaginatedObjects or AsyncManager in this net core implementation?

**Comment by zapadi** [comment]
The .net core version is async, so this is the reason you cannot find the AsyncManager. 
The GetPaginatedObjects is changed into GetPage.

Next week I'll do a push on dev.

**Comment by lferrao** [comment]
Thanks, looking forward to it!

**Comment by lferrao** [comment]
Did you ever push a new version to dev? I can't seem to find "GetPage".

**Comment by zapadi** [comment]
You can find the latest version on dev. For time being is working only for XML format.

**Comment by ToniIltanen** [comment]
Whats the status for .net core client?

**Comment by zapadi** [comment]
By the ned of the next week it will available.
