### ISSUE TITLE
Getting an issue related to project identifier

### ISSUE THREAD

**Issue by lasithc** [zapadi/redmine-net-api#168]
Hi,

I am trying to get an issue in a project. My code is,

var parameters = new NameValueCollection { { RedmineKeys.STATUS_ID, RedmineKeys.ALL } };
parameters.Add(RedmineKeys.PROJECT, project.Identifier);
var result = manager.GetObjects<Issue>(parameters);

Above code return result even when project identifier is not equal. i.e when debugging I checked the project property on issue (result[0].project) and that is not matching with project.Identifier I gave. 

Thanks!

**Comment by Chadiaw** [comment]
Hi, 

If you only want to get issues matching a given project id you have to use RedmineKeys.PROJECT_ID instead. 

I'm assuming project.Identifier is a string and you are calling GetObjects <Issue> (parameters), otherwise I don't think it will build.
