### ISSUE TITLE
Can'r create public projects

### ISSUE THREAD

**Issue by lasithc** [zapadi/redmine-net-api#169]
Hi,

With this API it is not possible to create a project with setting isPublic = true. 
I am using code,

Project newProject = <my created project with isPublic=true)
redmineManager.CreateObject(newProject);

The project is created but it is not public. 
Anyway I just did a HTTP POST callto redmine RestFul API with a Rest Client and via it I can create public projects. 

I wonder why this is not working with above code. 

Regards,
-Lasith Chandrasekara

**Comment by zapadi** [comment]
Hi,

Could you tell me what version of redmine are you using?

The is_public is exposed since 2.6.0.

**Comment by lasithc** [comment]
It is 3.1.1.stable
And redmine-api version is 1.0.4

**Comment by lasithc** [comment]
Hi Zapadi,

Thanks for the prompt response. Could you please let me know when you hope to release this fix, since it would help me to proceed. 

Regards

**Comment by zapadi** [comment]
Could you tell me what you get in fiddler when you create a project using the library?

I did some tests and it seems that the property is set corectly on server (the project was created with is_public = true) but the value is not comming back from the server.

**Comment by lasithc** [comment]
Hi,

I tried with Fiddler but I couldn't find request to localhost:3000 in it.
So I tried with TcpMon and it worked.

As I can see in the TCPMon it send relevant property is_public set to
"true" in the request. But in the response it is false.

Please find the attached screenshots.

1) These are the project properties that I passed to CreateObject method.

[image: පේළිගත පින්තූරය 1]

2) What I can find in TCPMon
[image: පේළිගත පින්තූරය 2]

3) Created project is not public
[image: පේළිගත පින්තූරය 3]

Regards,
-Lasith

2016-07-06 17:57 GMT+05:30 Padi <notifications@github.com>:

**Comment by lasithc** [comment]
Ok, I found the issue. it should be,
<is_public>true</is_public>
Not
<is_public>True</is_public>

Please note that "true" vs "True" is the issue

**Comment by zapadi** [comment]
This is fixed now in dev branch.
