### ISSUE TITLE
Can't create ProjectMembership

### ISSUE THREAD

**Issue by sajimon** [zapadi/redmine-net-api#170]
Hello, I'm having trouble project membership in selected project.

My code 

ProjectMembership newmem = new ProjectMembership
{
		User = new IdentifiableName { Name = "Marcin Sporysz"},
		Roles = new List<MembershipRole> { new MembershipRole { Id = 7 } },
		Project = new IdentifiableName { Id = 788 },

};
manager.CreateObject<ProjectMembership>(newmem, "pt1"); 

I'm getting an exception 
> Redmine.Net.Api.RedmineException: CreateObject has invalid or missing attribute parameters: Base can not be empty (i'm translating this message, so english version may not be exact)

Can you please assist me?

**Comment by zapadi** [comment]
Hello,

You should use user id and not user name

ProjectMembership newmem = new ProjectMembership
{
User = new IdentifiableName { Id =  <the id of "Marcin Sporysz">},
....

**Comment by sajimon** [comment]
Oh, that did the trick. Thank you!

**Comment by zapadi** [comment]
you are welcome.
