### ISSUE TITLE
Make versioning and packaging clearer and easier to understand

### ISSUE THREAD

**Issue by dfch** [zapadi/redmine-net-api#175]
Hi @zapadi we are actively using your library and find it very useful. However I had some confusion using the Nuget packages because of naming and versioning and I have some suggestions for clarification if it is ok with you.

=====
This repo consists of several projects for different .NET runtimes. The versioning from this repo leads to a nuget version that differs from the project version. Furthermore there is another nuget package with a different version that contains *signed* versions of this assembly. In addition there are no *releases* visible under Code/Releases.

I suggest the following:
* have a consistent versioning scheme (that ideally follows [semver](http://semver.org/))
* create a GitHub release for every release you intend to push to Nuget and keep the same version number for both
* fix the link to Nuget on the README on the front page of the Github page
* align Nuget package id with the project/repo id
* make clear what's the difference between the signed and the not-signed version of the repos
* keep same version number for signed and not-signed Nuget packages

![image](https://cloud.githubusercontent.com/assets/8310360/16941626/8d1fdb38-4d91-11e6-9136-c14d33be9e2e.png)

![image](https://cloud.githubusercontent.com/assets/8310360/16941613/7357e768-4d91-11e6-9f37-c1883fd89c72.png)

**Comment by zapadi** [comment]
Hello,

Thank you for your input.

I will try, by the end of the week, to release the new signed and unsigned versions of redmine-net-api. It will follow the semver versioning scheme.

**Comment by dfch** [comment]
@zapadi cool and thanks. If I can assist in any way, just let me know.

**Comment by zapadi** [comment]
Due to the fact that in the last 2 weeks I had no time to work on this project, I will postpone the release for next week.

**Comment by zapadi** [comment]
Fixed the followings:
* have a consistent versioning scheme (that ideally follows [semver](http://semver.org/))
* create a GitHub release for every release you intend to push to Nuget and keep the same version number for both
* fix the link to Nuget on the README on the front page of the Github page
* align Nuget package id with the project/repo id
* make clear what's the difference between the signed and the not-signed version of the repos
* keep same version number for signed and not-signed Nuget packages

**Comment by dfch** [comment]
very cool! thank you very much! Regards, Ronald
