### ISSUE TITLE
Add documents to a project

### ISSUE THREAD

**Issue by Hocdoc** [zapadi/redmine-net-api#177]
Is it somehow possible to add documents (file attachments) to a project with this API?
I cannot find anything for this in the docs or tests.

**Comment by zapadi** [comment]
You can upload documents and attach them to a specific issue.
https://github.com/zapadi/redmine-net-api/wiki/Upload-file

**Comment by Hocdoc** [comment]
Thanks for your answer, but I already knew how to attach files to a specific issue, but I want to add files ("documents") to a **project**. (In the GUI in Settings/Projects you can add "Documents" as a module/tab and then add attachments to projects.)

**Comment by zapadi** [comment]
Unfortunately, Redmine API does not support any other kind of upload.
http://www.redmine.org/projects/redmine/wiki/REST_API

**Comment by Hocdoc** [comment]
:-( Ok, thanks for this information.
