### ISSUE TITLE
Can't get attachments

### ISSUE THREAD

**Issue by zerg0s** [zapadi/redmine-net-api#178]
I call _GetObject<Issue>(..)_  to get an issue from hostedredmine, then trying to check its _Attachments_ property, it is always _null_. 

An "Issue"  itself is not _null_, I can use it as expected.
Also, this issue does have one attachment :)

**Comment by zapadi** [comment]
Please have a look at https://github.com/zapadi/redmine-net-api/wiki/Get-a-redmine-object.
You need to add include attachments parameter.

**Comment by zerg0s** [comment]
Thank you, just revised it in REST API of Redmine today, by default GET request also doesn't return attaches.
