### ISSUE TITLE
Issue Description Search

### ISSUE THREAD

**Issue by ricardoborges** [zapadi/redmine-net-api#179]
I would like to search issues by description field. Is it possible?

**Comment by zapadi** [comment]
No.  it is possible for subject.

**Comment by alinach** [comment]
For more information about searching by subject, please check [here](http://www.redmine.org/issues/13347)

In order to achieve this using redmine api, check the following example:

```
    string host = "<host>";
    string apiKey = "<api-key>";

    var manager = new RedmineManager(host, apiKey);
    var issues = manager.GetObjects<Issue>(new NameValueCollection { 
                          { "f[]=subject&op[subject]=~&v[subject][]","<texttofind>" } 
                        });

     foreach (var issue in issues)
     {
           Console.WriteLine("Issue: {0}.", issue);
     }
```

**Comment by ricardoborges** [comment]
That Works for description also... I've found an example not documented.

I can Post some code tomorrow

Em 2 de out de 2016 08:52, "alinach" <notifications@github.com> escreveu:

**Comment by ricardoborges** [comment]
If helps someone else:

            var p = new NameValueCollection();
            p.Add("project_id", "1");
            p.Add("set_filter", "1");
            p.Add("f[]", "description");
            p.Add("op[description]", "~");
            p.Add("v[description][]", descriptionValue);
            return _redmineManager.GetObjects<Issue>(p);

**Comment by zapadi** [comment]
I've done more tests and your solution is not working on redmine 2.5 but it's working on 3.x.x onwards.

**Comment by slcpunk** [comment]
This is working for me - but when I try to fillter for a PROJECT_ID, a TRACKER_ID AND a subject or description, it stops filtering the TRACKER.  Strange.  Try to explain better.  If I do this:


`             parameters.Add(RedmineKeys.PROJECT_ID, "1");`
`             parameters.Add(RedmineKeys.TRACKER_ID, "4");`
`             parameters.Add("set_filter", "1");`
`             parameters.Add("f[]", "subject");`
`             parameters.Add("op[subject]", "~");`
`             parameters.Add("v[subject][]", "AD");`
`             List<Issue> tlist = manager.GetObjects<Issue>(parameters);`

I get all trackers, not just those with ID 4.  If I remove the subject filter, I get only Tracker_ID = 4

**Comment by slcpunk** [comment]
Would love to know other operators too.  ~ searches for anything contained.  How about "starts with"?
