### ISSUE TITLE
support for mail_notification field

### ISSUE THREAD

**Issue by jobam** [zapadi/redmine-net-api#181]
Hello,
i added the mail_notification field support for User entity.
I would like to push my changes but the access is denied.

**Comment by zapadi** [comment]
Hello,
There is no Pull Request in pending. Did you create a pull request?

**Comment by jobam** [comment]
thanks for your answer.
Nope, i cannot push my branch so...

**Comment by jobam** [comment]
The error message:
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin mail_notification:mail_notification
Fatal: ArgumentException encountered.

remote: Permission to zapadi/redmine-net-api.git denied to jobam.

fatal: unable to access 'https://github.com/zapadi/redmine-net-api/': The requested URL returned error: 403

In fact you just have to give me the push right to the repository...

**Comment by jobam** [comment]
Sorry my bad.
Pull request is made.
