### ISSUE TITLE
Can't get Journal list

### ISSUE THREAD

**Issue by MrAngryBstrd** [zapadi/redmine-net-api#183]
Hello,
 i am trying to download Journals from my redmine server using this methods:

   ```
     NameValueCollection filters = new NameValueCollection()
        {
            { RedmineKeys.PROJECT_ID, projectid },
            { RedmineKeys.STATUS_ID, RedmineKeys.ALL },
            { RedmineKeys.INCLUDE, RedmineKeys.JOURNALS }
        };

        trackers.ToList().ForEach(t => filters.Add(RedmineKeys.TRACKER_IDS, t.ToString()));

        List<Issue> issues = redmine.GetObjects<Issue>(filters)
          .Where(i => i.Status.Name != "Rejected" && (i.Status.Name != "Closed" || i.ClosedOn >= DateTime.Now.Date.AddDays(-7))).ToList();
```

Anyway Journal element is always null.
Am I doing something wrong?

Thanks in advance.

**Comment by zapadi** [comment]
Hi,
It's not possible to get the journals when you retrieve all the issues. This option is available only when you get a specific issue.

**Comment by MrAngryBstrd** [comment]
Oh.. Ok thanks!
So the only way is to perform a cycle on issues and get journals for each one?
