### ISSUE TITLE
How to create objects with Custom Fields

### ISSUE THREAD

**Issue by ebartlomiej89** [zapadi/redmine-net-api#184]
Hi.

Can You tell me how can I add an Issue with Custom Field value?

Best Regards
Bartłomiej Ekiert

**Comment by zapadi** [comment]
Hi! Here it is.

string host = "<host>";
string apiKey = "<api-key>";

var manager = new RedmineManager(host, apiKey);

Issue issue = new Issue();
… issue.CustomFields = new List<IssueCustomField> {  new IssueCustomField { 

Id = "<custom-field-id>",
Values = new List<CustomFieldValue> {
new CustomFieldValue {Info = “<custom-field-value>”}}                     } } ; 

…
manager.CreateObject(issue);

**Comment by ebartlomiej89** [comment]
OK. When I add the Issue to Redmine using Connected RedmineManager i became an Exception.
**$exception	{"Internal Server Error"}	Redmine.Net.Api.Exceptions.InternalServerErrorException
with result code 500.**

I've been added the Existing Custom Fields with your code. My code look's that

**Issue issue= new Issue()
...
issue.CustomFields = new List<IssueCustomField>()
                    {
                        new IssueCustomField()
                        {
                        Id = Index,
                        Values = new List<CustomFieldValue>()
                        {
                            new CustomFieldValue()
                            {
                                Info = "Test")
                            }
                        }
                        }
                    };**

the index variable is the index of the CustomField from selected list of CustomFields using redmine get object 

**var Parameters = new NameValueCollection { { "project_id", ProjectId.ToString() }, { RedmineKeys.INCLUDE, RedmineKeys.RELATIONS } };
var CustomFields = ITSEB.Redmine.Controller.Redmine.RedmineConnection.GetObjects<CustomField>(Parameters);**

**Comment by ebartlomiej89** [comment]
OK, i solve problem, but now i have a problem with PosiibleCustomFieldValues

How to get a value list from specific custom field
I try get it that

**var Parameters = new NameValueCollection { { RedmineKeys.CUSTOM_FIELD, "10" } };
var CustomFieldValues = RedmineConnection.GetObjects(Parameters);**

and get exception:

**System.Collections.Generic.KeyNotFoundException: „CustomFieldPossibleValue”**
