### ISSUE TITLE
Problem with GetRedmineObjects<IssueCategory>()

### ISSUE THREAD

**Issue by ebartlomiej89** [zapadi/redmine-net-api#185]
Hi, when i Run this code after connection to Redmine via RedmineManager

**var Parameters = new NameValueCollection { { RedmineKeys.PROJECT_ID , ProjectID.ToString() } };
var Kategorie = ITSEB.Redmine.Controller.Redmine.RedmineConnection.GetObjects<IssueCategory>(Parameters);**

i receive a 0 values in list. The project ID = 4, and Exist in my Redmine.
Why I can't get list of IssueCategory?

**Comment by zapadi** [comment]
Hi,
Executing the following lines 

var issueCategories =
                fixture.RedmineManager.GetObjects<IssueCategory>(new NameValueCollection
                {
                    {RedmineKeys.PROJECT_ID, PROJECT_ID}
                });
returns the expected result.
