### ISSUE TITLE
Problem with get Project by name.

### ISSUE THREAD

**Issue by ebartlomiej89** [zapadi/redmine-net-api#187]
Hi.

Can you tell mi how to get project by it's name?

I try use this method.

var Parameters = new NameValueCollection() { { RedmineKeys.PROJECT, NAME } };
var projekt = Manager.Redmine.RedmineManager.GetObject<Project>(ID, Parameters);

NAME - string with name of project.

Second question is how to check that project exists?

**Comment by zapadi** [comment]
Hi.

1. To get the project by it's identifier:

```charp
var project = RedmineManager.GetObject<Project>("<PROJECT_IDENTIFIER | PROJECT_NAME>", null);
```
2. Using the same method and catching the RedmineException(NotFound).
