### ISSUE TITLE
Problem with create project

### ISSUE THREAD

**Issue by ebartlomiej89** [zapadi/redmine-net-api#188]
I want to add new project using your library. When I add it, then i get the exception:

Redmine.Net.Api.Exceptions.RedmineException
Redmine.Net.Api.Exceptions.RedmineException: CreateObject has invalid or missing attribute parameters: Identyfikator jest nieprawidłowe
 ---> System.Net.WebException: Serwer zdalny zwrócił błąd: (422) Unprocessable Entity.
   w System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   w System.Net.WebClient.UploadString(Uri address, String method, String data)
   w Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload[T](RedmineManager redmineManager, String address, String actionType, String data, String methodName)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w Redmine.Net.Api.Extensions.WebExtensions.HandleWebException(WebException exception, String method, MimeFormat mimeFormat)
   w Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload[T](RedmineManager redmineManager, String address, String actionType, String data, String methodName)
   w Redmine.Net.Api.RedmineManager.CreateObject[T](T obj, String ownerId)
   w Redmine.Net.Api.RedmineManager.CreateObject[T](T obj)
   w ITSEB.Redmine.Classess.ProjectData.DodajProjekt() w E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Redmine\Classess\ProjectData.cs:wiersz 51
   w ITSEB.Redmine.Classess.ProjectData.DodajProjekt(ProjectParams p) w E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Redmine\Classess\ProjectData.cs:wiersz 86
   w ITSEB.Common.Base.BaseController.InitRedmine(Func`1 _user, Func`1 _password) w E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Common.Base\BaseController.cs:wiersz 235
   w Template.Controller.<.ctor>b__2_10() w E:\TFS\ITSEB\Template (WinForms DX 17.1)\Template\Clasess\Controller.cs:wiersz 65
   w ITSEB.Common.Base.BaseController.InitLicence() w E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Common.Base\BaseController.cs:wiersz 212
   w ITSEB.Common.Base.BaseController.Init(Boolean WithGUI) w E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Common.Base\BaseController.cs:wiersz 106System.Net.WebException: Serwer zdalny zwrócił błąd: (422) Unprocessable Entity.
   w System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   w System.Net.WebClient.UploadString(Uri address, String method, String data)
   w Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload[T](RedmineManager redmineManager, String address, String actionType, String data, String methodName)

Please help me.

I set ID as a number and identifier as string.

**Comment by zapadi** [comment]
It seems, from the exception, that the identifier is invalid.

**Comment by ebartlomiej89** [comment]
Hmmm... how to resolve that problem?

**Comment by zapadi** [comment]
Could you show me the entire create new project call?
