### ISSUE TITLE
How to query between 2 time periods

### ISSUE THREAD

**Issue by guigui43** [zapadi/redmine-net-api#190]
below an example with tests :
var parameters = new NameValueCollection
{ 
{RedmineKeys.SPENT_ON, "=><,=2017-11-01,=2017-11-15" },  // {RedmineKeys.SPENT_ON, "=>2017-11-01,<2017-11-15" }, 
};
var timeEntries = Manager.GetObjects<TimeEntry>(parameters)

**Comment by zapadi** [comment]
operators containing ">", "<" or "=" should be hex-encoded so they're parsed correctly.

e.g.
1. date range (uncrypted filter is "><2012-03-01|2012-03-07")
var parameters = new NameValueCollection
{
{RedmineKeys.SPENT_ON, "%3E%3C2012-03-01|2012-03-07" }, 
};
