### ISSUE TITLE
how to get all the TimeEntry??

### ISSUE THREAD

**Issue by EmilioLopez55** [zapadi/redmine-net-api#197]
how to get all the TimeEntry??

var parametersTimeEntry = new NameValueCollection { { RedmineKeys.USER_IDS,RedmineKeys.ALL } };

only get TimeEntry of a user

**Comment by zapadi** [comment]
```
redmineManager.GetObjects<TimeEntry>(null);
```

**Comment by EmilioLopez55** [comment]
I put in the null value and it only leaves the time of a user, does it have to do with the API?
