### ISSUE TITLE
 NameValueCollection parametersTimeEntries = null; just get one time task from one user

### ISSUE THREAD

**Issue by EmilioLopez55** [zapadi/redmine-net-api#198]
I put in the null value and it only leaves the time of a user, does it have to do with the API?

![imagen](https://user-images.githubusercontent.com/35222636/35474366-b62b922a-038d-11e8-8c82-2fa6f030929e.png)
![imagen](https://user-images.githubusercontent.com/35222636/35474375-cbdcf168-038d-11e8-8676-2c3b8b91cc92.png)

The 85 tasks of time are from cristobal lopez fernandez, it does not show the times of my tasks, for example

**Comment by zapadi** [comment]
You can get the time entries like:
```
var allTimeEntries = redmineManager.GetObjects<TimeEntry>();
var projectTimeEntires = redmineManager.GetObjects<TimeEntry>(new NameValueCollection {{ RedmineKeys.PROJECT_ID, PROJECT_ID }});
var userTimeEntries = redmineManager.GetObjects<TimeEntry>(new NameValueCollection { { RedmineKeys.USER_ID, "6" } }); //user with id 6
```
