### ISSUE TITLE
CreateObject<Issue> 403 Forbidden

### ISSUE THREAD

**Issue by ebartlomiej89** [zapadi/redmine-net-api#199]
Hi

I create an user, and assign it to a project. After this operation create a RedmineManager connection via created user (string URL, string User, string Password). After login I can't create issue. I have 403 response.

Please help me.

Redmine.Net.Api.Exceptions.ForbiddenException
Redmine.Net.Api.Exceptions.ForbiddenException: Forbidden ---> System.Net.WebException: Serwer zdalny zwrócił błąd: (403) Zabronione.
   w System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   w System.Net.WebClient.UploadString(Uri address, String method, String data)
   w Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload[T](RedmineManager redmineManager, String address, String actionType, String data, String methodName)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w Redmine.Net.Api.Extensions.WebExtensions.HandleWebException(WebException exception, String method, MimeFormat mimeFormat)
   w Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload[T](RedmineManager redmineManager, String address, String actionType, String data, String methodName)
   w Redmine.Net.Api.RedmineManager.CreateObject[T](T obj, String ownerId)
   w Redmine.Net.Api.RedmineManager.CreateObject[T](T obj)
   w ITSEB.Redmine.Classess.IssueData.DodajZagadnienie() w E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Redmine\Classess\IssueData.cs:wiersz 63
   w ITSEB.Redmine.Classess.IssueData.DodajZagadnienie(IssueParams i) w E:\TFS\ITSEB\ITSEB.Common (WinForms 17.1)\ITSEB.Redmine\Classess\IssueData.cs:wiersz 93
   w Jira2Redmine.Forms.Form1.CreateTicket(IssueData i) w E:\TFS\ITSEB\Jira to Redmine importer\Jira2Redmine\Forms\Form1.cs:wiersz 619System.Net.WebException: Serwer zdalny zwrócił błąd: (403) Zabronione.
   w System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   w System.Net.WebClient.UploadString(Uri address, String method, String data)
   w Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload[T](RedmineManager redmineManager, String address, String actionType, String data, String methodName)

**Comment by zapadi** [comment]
Is *Enable REST API* in Administration -> Settings -> Authentication checked?

**Comment by ebartlomiej89** [comment]
Yes, I have checked it. I identify project by ID.

**Comment by zapadi** [comment]
Redmine version?

**Comment by ebartlomiej89** [comment]
3.4.4
