### ISSUE TITLE
getting user duplicates when user has public key

### ISSUE THREAD

**Issue by WalserAndreas** [zapadi/redmine-net-api#208]
Dear Sir or Madam,
with the Redmine API it should be possible to get all aktiv User from Redmine. 
But apparently there is an issue with the function if you have the GitHub plugin.
The function in the attachment is written by myself with the Redmine API (dotNet 4.52).
If you try to get all aktiv user from Redmine and some of the user have a key for the GitHub plugin, the userid with the key is not returned. Instead of the right userid another userid is returned twice. 
Because of this it looks like you get the right amount of aktive users but you just get a lot of duplicates.
Also if you try to get the status of a user you get no response if the user has a key for the GitHub plugin.
Has anyone had a similar behavior with the Rest API or can provide a solution for this situation?

Best regards
Walser Andreas

[function.txt](https://github.com/zapadi/redmine-net-api/files/2025831/function.txt)

**Comment by zapadi** [comment]
Hi,
I'm not sure I understand the issue.

Could you give me more details.
