### ISSUE TITLE
nuget new build process

### ISSUE THREAD

**Issue by konne** [zapadi/redmine-net-api#210]
Hi,

your build process is at the moment complex because the old csproj doesn't support multi target builds.
Do you like that I make a PR to change to the new cprojs with <targetframeworks> ?

bye

**Comment by zapadi** [comment]
Please do.

**Comment by konne** [comment]
Hi, I just wondering about some differences in the build between different .NET / signed releases.
I will now try to merge it in the right way, but maybe we need after that a short session together to clariy the last open points

**Comment by zapadi** [comment]
When would you like to have it?

**Comment by konne** [comment]
I'm in Germany so any time between 7:30-16:00CET is fine. Does this fit for you?

**Comment by zapadi** [comment]
It's perfect. Please, send me a meeting link.

**Comment by konne** [comment]
@zapadi 
09.08. 10:00-10:30
https://go.teamviewer.com/v13/m29470043

**Comment by zapadi** [comment]
Hi,

There is a big refactoring in progress right now, but I'm not sure that will be available by next month.

Any contribution it will speed up the process.


Adrian

**Comment by ekwus** [comment]
Hey

I found your redmine-netcore-api project and have got that working for now.

If you have specific tasks that can be branched off easily then let me know what they are and I'll take a look at them?

Cheers

Dave
