### ISSUE TITLE
using Newtonsoft

### ISSUE THREAD

**Issue by konne** [zapadi/redmine-net-api#212]
@zapadi 
Is there a reason why you wrote the JSON Deserializing by hand and don't use the automatic way of Newtonsoft?
This would also allow to support .NET 2.0?

**Comment by zapadi** [comment]
I didn't want to have external dependencies(control freak, probably :) ). 

The .net core version https://github.com/zapadi/redmine-netcore-api is using Newtonsoft.

**Comment by konne** [comment]
okay, just for your info, I try also to get the "core" build into the common nuget compile process.
Otherwise you get crazy to take care of the project.
