### ISSUE TITLE
ATTACHMENTS - Deserialization error

### ISSUE THREAD

**Issue by elisandrom** [zapadi/redmine-net-api#220]
Hi,
When include Attchments, show error : "Deserialization error"
Code:
`return managerRedmine.GetObject<Issue>(number, new NameValueCollection {
                    { RedmineKeys.INCLUDE, RedmineKeys.ATTACHMENTS }
                });`

**Comment by zapadi** [comment]
Hi,
Could you show me the xml (json) response from the server?

Thanks,
