### ISSUE TITLE
How to ignore a server that uses a self-signed certificate?

### ISSUE THREAD

**Issue by yahch** [zapadi/redmine-net-api#221]
I am using redmine in the LAN, it uses the self-signed certificate of HTTPS, I use the following code to connect.
```java
 string host = "https://sangfor.35581a588e4be84467854118a954558f57733.com:7443/redmine/";
 string apiKey = "5a577b56ead04824af2b145562218780";
 string issueId = "10256";
 // dont't verify cert,cause it's a self-signed cert
 var manager = new RedmineManager(host, apiKey, MimeFormat.Json, false);

 //parameter - fetch associated relations.
 var parameters = new NameValueCollection { { RedmineKeys.INCLUDE, RedmineKeys.RELATIONS } };

 var issue = manager.GetObject<Issue>(issueId, parameters);
 Console.WriteLine("Issue: {0}.", issue);
```
but it did't work and shows error below:
```
The underlying connection has been closed: A trust relationship could not be established for the SSL/TLS secure channel.
```

**Comment by yahch** [comment]
ok,I resolved by myself,tanks.

just add some code to make HttpWebRequest to ignore cert validation.

```cs
ServicePointManager.ServerCertificateValidationCallback =
delegate (Object obj, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors) { return true; };
```

**Comment by lpereira98** [comment]
I'm having the same issue.
Is there any way to ignore cert validation for the RedmineManager and RedmineWebClient object?
Using .net framework 4.0

**Comment by yahch** [comment]
> I'm having the same issue.
> Is there any way to ignore cert validation for the RedmineManager and RedmineWebClient object?
> Using .net framework 4.0

modify source code.find where HttpWebRequest and then add ignore validation callback like my comment above :)
