### ISSUE TITLE
List<ProjectMembership> Error 404

### ISSUE THREAD

**Issue by ebartlomiej89** [zapadi/redmine-net-api#223]
When I run this code to get project membership i get the 404 error:
```
var Parameters = new NameValueCollection() { { RedmineKeys.PROJECT_ID, ID } };
List<ProjectMembership> d = Manager.Redmine.RedmineManager.GetObjects<ProjectMembership>(Parameters);
```
This is an exception for this code:
Redmine.Net.Api.Exceptions.NotFoundException: „Not Found ”

  | Nazwa | Wartość | Typ
-- | -- | -- | --
  | StackTrace | "   w Redmine.Net.Api.Extensions.WebExtensions.HandleWebException(WebException exception, String method, MimeFormat mimeFormat)\r\n   w Redmine.Net.Api.Internals.WebApiHelper.ExecuteDownloadList[T](RedmineManager redmineManager, String address, String methodName, NameValueCollection parameters)\r\n   w Redmine.Net.Api.RedmineManager.GetPaginatedObjects[T](NameValueCollection parameters)\r\n   w Redmine.Net.Api.RedmineManager.GetObjects[T](NameValueCollection parameters)\r\n   w ITSEB.Redmine.Classess.ProjectMembers.ListaOsobWProjekcie(String ID) w D:\\DEV\\ITSOLUTIONS\\TFS-VS17\\ITSEB Common Forms 17.1\\ITSEB.Redmine\\Classess\\ProjectMembers.cs:wiersz 44\r\n   w Jira2Redmine.Forms.Form1.UsersMap(Int32 ID) w D:\\DEV\\ITSOLUTIONS\\TFS-VS17\\Jira to Redmine Importer\\Jira2Redmine\\Forms\\Form1.cs:wiersz 823\r\n   w Jira2Redmine.Forms.Form1.btnIssuesSend_ItemClick(Object sender, ItemClickEventArgs e) w D:\\DEV\\ITSOLUTIONS\\TFS-VS17\\Jira to Redmine Importer\\Jira2Redmine\\Forms\\Form1.cs:wiersz 753\r\n   w DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)\r\n   w DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)\r\n   w DevExpress.XtraBars.BarItemLink.OnLinkClick()\r\n   w DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)\r\n   w DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)\r\n   w DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)\r\n   w DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnUnPressItem(DXMouseEventArgs e, RibbonHitInfo hitInfo)\r\n   w DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnMouseUp(DXMouseEventArgs e)\r\n   w DevExpress.XtraBars.Ribbon.Handler.RibbonHandler.OnMouseUp(DXMouseEventArgs e)\r\n   w DevExpress.XtraBars.Ribbon.RibbonControl.OnMouseUp(MouseEventArgs e)\r\n   w System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)\r\n   w System.Windows.Forms.Control.WndProc(Message& m)\r\n   w DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)\r\n   w DevExpress.XtraBars.Ribbon.RibbonControl.WndProc(Message& m)\r\n   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)" | string

Redmine version: 4.0.2
Redmine .NET SDK Version: 2.0.37

**Comment by zapadi** [comment]
Is this still an open issue?
