### ISSUE TITLE
How to add an  issue trackers(Bag,Feature,Support) to the existing  project?(c#)

### ISSUE THREAD

**Issue by vvdvortsova** [zapadi/redmine-net-api#224]
Please, help to solve
var project = manager.GetObject<Project>(project_id, null);
			project.Description = "Updated description";
			ProjectIssueCategory proCat = new ProjectIssueCategory();
			proCat.Id = 10;
			proCat.Name = "Feature";
			project.IssueCategories = new List<ProjectIssueCategory>();
			project.IssueCategories.Add(proCat);
			project.Trackers = new List<ProjectTracker>();
			
			project.Trackers.Add(new ProjectTracker(){Name = "Bag"});
			manager.UpdateObject(project_id, project);
			var updatedProject = manager.GetObject<Project>(project_id, null);
			Console.WriteLine("Updated issue: {0}.", updatedProject);
//This cod doesn't add trackers
![RedmineProject](https://user-images.githubusercontent.com/43184829/57524501-9bbd2700-7330-11e9-83ad-875a9eff4dad.png)
kers

**Comment by zapadi** [comment]
Try this:
```
project.Trackers.Add(new ProjectTracker(){Id = <bug_tracker_id> },
new ProjectTracker(){Id = <feature_tracker_id> },
new ProjectTracker(){Id = <support_tracker_id> });
manager.UpdateObject(project_id, project);
```

**Comment by zhougang2046** [comment]
> Please, help to solve
> var project = manager.GetObject(project_id, null);
> project.Description = "Updated description";
> ProjectIssueCategory proCat = new ProjectIssueCategory();
> proCat.Id = 10;
> proCat.Name = "Feature";
> project.IssueCategories = new List();
> project.IssueCategories.Add(proCat);
> project.Trackers = new List();
> 
> ```
> 		project.Trackers.Add(new ProjectTracker(){Name = "Bag"});
> 		manager.UpdateObject(project_id, project);
> 		var updatedProject = manager.GetObject<Project>(project_id, null);
> 		Console.WriteLine("Updated issue: {0}.", updatedProject);
> ```
> 
> //This cod doesn't add trackers
> ![RedmineProject](https://user-images.githubusercontent.com/43184829/57524501-9bbd2700-7330-11e9-83ad-875a9eff4dad.png)
> kers

Hello, I also encountered the same problem, how did you solve it? Thank you

**Comment by zapadi** [comment]
You need to use tracker's id instead of tracker's name.
