### ISSUE TITLE
'Could not deserialize null!' When update WikiPage

### ISSUE THREAD

**Issue by Bas-vE** [zapadi/redmine-net-api#225]
When I run this code:

`            _manager = new RedmineManager(host, apiKey);
            var user = _manager.GetCurrentUser();

            var projectName = "vitplayground";
            var wikiPageName = "API created page";

            var page = _manager.GetAllWikiPages(projectName).Where(o => o.Title == wikiPageName).FirstOrDefault();
            if (page == null)
            {
                page = new WikiPage { Text = $"{DateTime.Now.TimeOfDay} This is a test", Comments = "This is a comment" };
            }
            else
            {
                page.Text = $"{DateTime.Now.TimeOfDay} This is a test";
            }

            _manager.CreateOrUpdateWikiPage(projectName, wikiPageName, page);`

I'm getting a Redmine.Net.Api.Exceptions.RedmineException: 'Could not deserialize null!' on the CreateOrUpdateWikiPage method. But it only happens if the page already exists. I have no idea what i'm doing wrong. Creating a new page works but when i'm adding a new file to the page i'm getting the same exception.

**Comment by zapadi** [comment]
I'll check it and let you know. What version of redmine are you using?

**Comment by Bas-vE** [comment]
Our redmine is hosted by Planio and they say it runs on version 3.3.2

**Comment by Bas-vE** [comment]
So I just figured out that calling GetAllWikiPages() and filtering out the page you want returns an incomplete page. I think this is part of the main problem. There is a lot of page information (text, author and more) missing after fetching the pages like this. 

When I use the GetWikiPage() method, it works just fine.

**Comment by zapadi** [comment]
Right now I'm refactoring the entire library and I already solved quite a few issues. I will check this one as well.
