### ISSUE TITLE
Retrieving tasks

### ISSUE THREAD

**Issue by kasilioglu** [zapadi/redmine-net-api#228]
Hi, thanks for great library.
We're using tags plugin. Basically we add multiple tags like 'abc, xyz'. When we fetch issues those values are not exist in custom fields. However if i query with "tags" key i get related issues.

Is there a way to get those tags withing Issues and also adding tags while creating-updating ?

**Comment by zapadi** [comment]
Hi, thanks for  the kind words.

If you have a query an already defined query for fetchning the issues related to defined tags, you can add "query_id" to fetch paramets.

**Comment by kasilioglu** [comment]
Hi, thats right, can get all issues with specific tag by querying with query_id.
And i suppose its impossible to  read-write the tags on an issue with the api.
Thanks
