### ISSUE TITLE
Set Issue's Custom Category of type User

### ISSUE THREAD

**Issue by Coolfeather2** [zapadi/redmine-net-api#230]
Trying to set the custom category of type User

What does the redmine-net-api want as the input to set the Category of type "user"?  
I've tried the following as strings:

- FirstnameLastname
- Firstname Lastname
- Firstname.Lastname@domain.com

Thanks

**Comment by zapadi** [comment]
You should set the category id 
```
issue.Category = new IdentifiableName(){Id = <user_id>}. 

```

**Comment by Coolfeather2** [comment]
Sorry, this is for a CustomField though

**Comment by Coolfeather2** [comment]
Solution?
```C#
newIssue.CustomFields = new List<IssueCustomField>
{
    new IssueCustomField
    {
        Id = 10, Values = new List<CustomFieldValue> //Set Field ID
        {
            new CustomFieldValue { Info = <user_id>} //Set Field Contents
        }
    }
};
```
