### ISSUE TITLE
GetObject / UpdateObject <Project> with inherit_members

### ISSUE THREAD

**Issue by AlexSinav** [zapadi/redmine-net-api#233]
There is a bug (or lack of feature) in Redmine REST API "GET /projects/[id].xml". It doesn't return inherit_members field value of project (https://www.redmine.org/issues/32002). But this field can be updated by "PUT /projects/[id].xml".
When using redmine-net-api to update some properties of existing Redmine Project object at first we get it by GetObject<Project> and InheritMembers is always false. Even if it is set to true in Redmine. Next by executing UpdateObject<Project> we are updating Redmine Project and inherit_members is setting to false. And this is not right.
This is not a bug of redmine-net-api, but it's very uncomfortable.
Is there a way to get round this problem?
May be doesn't update InheritMembers with UpdateObject<Project>?

**Comment by zapadi** [comment]
InheritMembers update will be disabled until the redmine issue will be fixed.

**Comment by AlexSinav** [comment]
Zapadi, thank you.
Guys from Redmine will fix it in release 4.1.0
