### ISSUE TITLE
Exception on creating a new time entry

### ISSUE THREAD

**Issue by startsevsa** [zapadi/redmine-net-api#235]
![image](https://user-images.githubusercontent.com/14212283/67151548-327b1000-f2e1-11e9-8682-51751f6f691a.png)
Library worked good, but exception appeared after moving to a new computer with clear system.

**Comment by startsevsa** [comment]
maybe this can help:
https://stackoverflow.com/questions/1326039/what-types-of-exceptions-can-the-xmlserializer-deserialize-method-throw

**Comment by zapadi** [comment]
Hi,

Could you tell me what version of .NET Framework and Redmine are you using?
