### ISSUE TITLE
User update return 500 status

### ISSUE THREAD

**Issue by mrv66** [zapadi/redmine-net-api#236]
Hi, I'm using redmine-api 2.0.43. I'm trying to update user name, but I get 500 status in exception. Here my code
```
try
{
	string host = "hostname";
        string apikey = "apikey";
        var manager = new RedmineManager(host, apikey);
        var userId = "userId";
        var user = manager.GetObject<User>(userId, null);
        user.FirstName = "some name";
        manager.UpdateObject<User>(userId, user);
}
catch (Exception ex)
{
}
```
What I'm doing wrong?

**Comment by zapadi** [comment]
Hi,

You have to provide the following attributes (mandatory):
the user login, firstname , lastname, mail

Let me know if you still have the issue after you provide the required attributes.

**Comment by mrv66** [comment]
I have admin privileges. I'm trying to update existsing user and login, firstname , lastname, mail, all of these attributes are filled by GetObject method
`var user = manager.GetObject<User>(userId, null);`

**Comment by zapadi** [comment]
what version of redmine are you using?

**Comment by mrv66** [comment]
4.0.4
