### ISSUE TITLE
Use Apache Basic Auth return Unautholized

### ISSUE THREAD

**Issue by k-oshiro0322** [zapadi/redmine-net-api#237]
Hi, I'm using redmine-net45-api Version 2.0.43.0. thank you nice application!
In our environment, we use Apache Baic authentication.
I'm trying two pattern, But response Unautholized error.

Is there any solution?

pattern1:Embedded in URL .
```
try{
  var redmine = new RedmineManager(host: "http://basicid:basicpass@my-redmine.com", apiKey: "XXXXXXXXXXXXXXX");

  var issue = redmine.GetObject<Issue>("1", new NameValueCollection { { "include", "children,attachments,relations,changesets,journals,watchers" } });
catch (Exception ex){
  Console.WriteLine(ex.Message); //Unautholized
}
```

pattaern2:in Header.
```
try{
  var redmine = new RedmineManager(host: "http://basicid:basicpass@my-redmine.com", apiKey: "XXXXXXXXXXXXXXX");
  var webClient = redmine.CreateWebClient(new NameValueCollection { { "include", "children,attachments,relations,changesets,journals,watchers" } });
  webClient.Headers.Add("Authorization", "Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
  var issue = redmine.GetObject<Issue>("1", new NameValueCollection { { "include", "children,attachments,relations,changesets,journals,watchers" } });
catch (Exception ex){
  Console.WriteLine(ex.Message); //Unautholized
}
```

**Comment by zapadi** [comment]
Hi, 

For the first pattern:
1. Make sure your apiKey is valid 

For the seccond pattern:

1. The header key is "X-Redmine-API-Key" instead of "Authorization"
2. In order to properly forward basic authentication the following rewrite rule is necessary in .htaccess (Apache and fastcgi):
RewriteRule ^(.*)$ dispatch.fcgi [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]

3. For "Authorization" key you have to use the other ctor (eg. new RedmineManager(string host, string login, string password,...)

**Comment by k-oshiro0322** [comment]
Thank you for your replay.
I was wrong about login and password in the constructor.

I'm tried second pattern.I'm changed the timing of passing APIKey at the time of GetObject().

```
/// APIKey:XXX
/// basic auth login id: id
/// basic auth login passwd: Password

try{
  var redmine = new RedmineManager(host: "http://my-redmine.com", login: "id", password: "Password");
  var nvc = new NameValueCollection { { "key", "XXXX" } };
  var issue = redmine.GetObject<Issue>("1", nvc); //OK
  
catch (Exception ex){
  Console.WriteLine(ex.Message); //Unautholized
}
```

But, I occued next problem...
I want to call UpdateObject(). This is not send NameValueCollection.
I think UpdateAttachment() has the same worry.
Are you sure I want to create a pull request?

**Comment by zapadi** [comment]
Do we need NameValueCollection for the update?

Go ahead with the pull request.
