### ISSUE TITLE
compile error after updating from 2.x to 3.x

### ISSUE THREAD

**Issue by muffmolch** [zapadi/redmine-net-api#243]
I have trouble with assigning Uploads and CustomFiles to a new issue:

set properties are changed to internal:

```
Issue issue = new Issue();
CurrentIssue.Uploads = uploads;
```
and:

```
if(CurrentIssue.CustomFields == null) {
   CurrentIssue.CustomFields = new List<IssueCustomField>();
}
CurrentIssue.CustomFields.Add(modul);
```
What's the solution for this?

Furthermore I have to change that fileds for existing issues...

Here's a example code taken from your tutorial:
```

//create issue and attach the document
Issue issueWithAttachment = redmineManager.CreateObject<Issue>(
                                            new Issue 
                                            {
                                                Project = project,
                                                Subject = "Issue with attachment",
                                                Uploads = attachments
                                            });
```

same problem. Please hekp me, I really like your Redmine-Lib!

**Comment by muffmolch** [comment]
@zapadi: +1 Many thanks. Great lib!!!

**Comment by muffmolch** [comment]
anyway. Is there a changeset overview between 2.x and 3.x?

**Comment by zapadi** [comment]
> @zapadi: +1 Many thanks. Great lib!!!

Thank you.

**Comment by zapadi** [comment]
> anyway. Is there a changeset overview between 2.x and 3.x?

I'm using semantic version and I've done some incompatible API changes.
I'll try to keep updated the changelog.
