### ISSUE TITLE
Geting Subtasks

### ISSUE THREAD

**Issue by RogerioTostes** [zapadi/redmine-net-api#244]
Hi

Could you help me?how to get the subtaks?

![image](https://user-images.githubusercontent.com/40499106/70649683-69f4a180-1c2c-11ea-8bbf-d2f71f5c4d7a.png)

**Comment by zapadi** [comment]
Hi,
Use subproject_id to get issues from the subproject with the given id. 
Use project_id=XXX&subproject_id=!* to get only the issues of a given project and none of its subprojects.
Use subproject_id=* to get all the issues of all the subprojects(not tested)
