### ISSUE TITLE
Empty response on CreateOrUpdateWikiPage

### ISSUE THREAD

**Issue by Sa1Gur** [zapadi/redmine-net-api#245]
Hi!
CreateOrUpdateWikiPage creates (or updates) WikiPage but throws the exception "Could not deserialize null!" afterward. I check out the repo and tried to manually debug it. Turns out - response in  WebApiHelper.cs (T ExecuteUpload<T>  line 81: var response = wc.UploadString ) is empty. I tried to use Redmine Rest Api directly and it worked ok. I have received a response 200.

I use .Net 4.0 in my project (app for W10 x64 ). Redmine version  4.0.5.stable

**Comment by Sa1Gur** [comment]
Hi!
I debugged UploadString behavior in this scenario and found that 200 response is received in GetWebResponse() function, but the response.ContentLength == -1. So, naturally, we got empty string. I think it is reasonable eigther not to process response string in cases it is not needed (I check in error cases - exception will be thrown) or use HttpClient instead of WebClient.

**Comment by zapadi** [comment]
Hi!
I'm refactoring the that part to handle cases like the one mentioned.

**Comment by Sa1Gur** [comment]
Great! Thank you!
