### ISSUE TITLE
Issue API fails with 3.0.6 package

### ISSUE THREAD

**Issue by tobster-de** [zapadi/redmine-net-api#250]
The sync example 
https://github.com/zapadi/redmine-net-api/wiki/Get-a-redmine-object
fails with the current 3.0.6 package. (sorry for the german details)

> Redmine.Net.Api.Exceptions.RedmineException
>   HResult=0x80131500
>   Nachricht = Deserialization error
>   Quelle = redmine-net-api
>   Stapelüberwachung:
>    bei Redmine.Net.Api.Internals.RedmineSerializer.Deserialize[T](String response, MimeFormat mimeFormat)
>    bei Redmine.Net.Api.Internals.WebApiHelper.ExecuteDownload[T](RedmineManager redmineManager, String address, String methodName, NameValueCollection parameters)
>    bei Redmine.Net.Api.RedmineManager.GetObject[T](String id, NameValueCollection parameters)
>    bei Redmine.Program.Main(String[] args) in C:\Users\tgaer\Documents\Visual Studio 2017\Projects\Redmine\Redmine\Program.cs: Zeile23
> 
> Innere Ausnahme 1:
> InvalidOperationException: Fehler im XML-Dokument (1,1451).
> 
> Innere Ausnahme 2:
> ObjectDisposedException: Von einem geschlossenen TextReader kann nicht gelesen werden.
> 

I compiled the current sources myself and did not get the exception. Do you have any clues regarding this behavior? Are you planning to release a new package in the near future?

**Comment by zapadi** [comment]
Hi,
I've published the latest changes.

**Comment by tobster-de** [comment]
Thanks again
