### ISSUE TITLE
Get a batch of issues

### ISSUE THREAD

**Issue by tobster-de** [zapadi/redmine-net-api#251]
In the redmine API docs I found the hint that it is possible to request multiple issues at once. 

see https://www.redmine.org/projects/redmine/wiki/Rest_Issues 

> GET /issues.xml?issue_id=1,2

Is it possible to use this currently? I did not find an appropriate method overload.

**Comment by zapadi** [comment]
Hi,
Yes, it's possible.
```
var rm = new RedmineManager(...);
var issues = rm.GetObjects<T>( new NameValueCollection(){{"issue_id","1,2"}});
```

**Comment by tobster-de** [comment]
Thank you
