### ISSUE TITLE
Version 3.0.6.1 makes IssueCustomField.Info readonly breaking existing usage

### ISSUE THREAD

**Issue by Knitter** [zapadi/redmine-net-api#253]
Hi,

I'm not sure how to migrate to the new version as it makes some fields readonly that were previously used to create or update data. e.g. how should we now update the value of an IssueCustomField with .Info?

I didn't find an issue or wiki related to this question so bit uncertain what is the expected upgrade path

**Comment by AlexeyMAGician** [comment]
+1
@zapadi, I have the same question!
Most base classes like "Identifiable<T>", now have "protected internal set" for "Id".
How it use?

**Comment by KEMAL-YILDIRIM** [comment]
I am having the same issue and overcome it by
```
public class RedmineIdentifiableName : IdentifiableName
	{
		public RedmineIdentifiableName(int id)
		{
			base.Id = id;
		}

	}
```

**Comment by muffmolch** [comment]
same here ... why????

**Comment by zapadi** [comment]
> +1
> @zapadi, I have the same question!
> Most base classes like "Identifiable", now have "protected internal set" for "Id".
> How it use?

The idea behind removing most of the setters is  to follow the serialization process.  If the properties of a redmine entity are not expected by the server, those properties should not have public setters.
The case of identifiable is the same: the ids are assigned by the server. 

One of the solutions, for the moment, is to do it like @KEMAL-YILDIRIM did. 

If you have a better idea or approach, please, let me know.

**Comment by derek2132** [comment]
I had the same problem when using this .
I did a seach first and then assign the value to the new one .
I'm tied.

**Comment by derek2132** [comment]
> public class RedmineIdentifiableName : IdentifiableName
> 	{
> 		public RedmineIdentifiableName(int id)
> 		{
> 			base.Id = id;
> 		}
> 
> 	}

Good job!
