### ISSUE TITLE
Help me with create issues api redmine. Error is The property or indexer 'Identifiable<IdentifiableName>.Id' cannot be used in this context because the set accessor is inaccessible

### ISSUE THREAD

**Issue by amo82** [zapadi/redmine-net-api#254]
Hello
I create a simple Hello World app with api net redmine.
When create var newIssues, appear this error 
Example

```
 var newIssue = new Issue();
            newIssue.Subject = "test rest API";
            newIssue.Description = "New Ads from Rest API";
            issue.Project = new IdentifiableName() {Id = 5 };   //This line error is The property or indexer 'Identifiable<IdentifiableName>.Id' cannot be used in this context because the set accessor is inaccessible
```
I hope for your help
Thank you

**Comment by zapadi** [comment]
Hello,
One option is to do it like @KEMAL-YILDIRIM suggested #253 or to make a wrapper and in this case the future changes will not impact you too much.

**Comment by derek2132** [comment]
Hello
You can now use tha latest version 4.0 to do like below.
      IdentifiableName.Create<IdentifiableName>(id)

**Comment by muffmolch** [comment]
> Hello
> You can now use tha latest version 4.0 to do like below.
> IdentifiableName.Create(id)

So good!!!! I like :-)
