### ISSUE TITLE
Cannot set the status of a project

### ISSUE THREAD

**Issue by martinzumarraga** [zapadi/redmine-net-api#255]
Hello,
I am trying to set the status of a project as follows:

 
```
Redmine.Net.Api.Types.Project project = new Redmine.Net.Api.Types.Project
            {
               Name = name,
               Identifier = projectIdentifier,
               Description = description,
               IsPublic = false,
               InheritMembers = false,
               Status = ProjectStatus.Close
            };

Redmine.Net.Api.Types.Project savedProject = redmineManager.CreateObject(project);
```

I have also tried to update it:

```
var redmineProject = redmineManager.GetObject<Project>(projectIdentifier, null);
redmineProject.Status = ProjectStatus.Close;
redmineManager.UpdateObject(projectIdentifier, redmineProject);
```

In both cases the status is not updated, so I am wondering whether it exists another way to do so or not. The Redmine repository version that I am using is the 4.0.5.

I hope you can help me. Thank you.

**Comment by zapadi** [comment]
Hello,
What version of Redmine, Redmine .NET API are you using?

**Comment by martinzumarraga** [comment]
Hello and thank you for your answer,

The versions I am using are:
- Redmine 4.0.5.
- .NET API 3.0.0

**Comment by zapadi** [comment]
The status property is not serialized because is not expected by the server.
