### ISSUE TITLE
Unexpected ArgumentNullException in RedmineManager.cs:581

### ISSUE THREAD

**Issue by peck199** [zapadi/redmine-net-api#259]
Hi,

an unexpected ArgumentNullException occurs when RedmineManager.GetObjects is called and the resulting list is empty.

In my case the ProjectMemberships are checked to be available. Since there are no, the resulting list from the server is empty. The extension method ReadElementContentAsCollection.ReadElementContentAsCollection() returns null, when there isn't at least one element (because the result-list is initialized late). Therefor in RedmineManager.cs:576 the tempResult is not null, but tempResult.Items is.

This could be fixed with a null check in XmlReaderExtensions.ReadElementContentAsCollection():179, right after ReadStartElement(), because in that case it's sure, the server responded with data, even if the list is actually empty. In cases where no start element is transmitted, returning null is appropriate.

Thanks

**Comment by zapadi** [comment]
Hi,
I will gladly accept pull request.
