### ISSUE TITLE
Issue with 'relates" relation

### ISSUE THREAD

**Issue by charettemtb** [zapadi/redmine-net-api#262]
Hello,
first of all, thank you for your job!
I'm using redmine version : 4.0.4 and the api in version 3.0.6.1 (nugets current version).

I think there is a bug with IssueRelation creation.
There is the payload sent by the api :
`<relation>
<issue_to_id>foo</issue_to_id>
<relation_type>Relates</relation_type>
</relation>`

With that the server responds with an error (confirmed with postman).

Now with postman if I replace **Relates** by **relates**, according to the [documentation](https://www.redmine.org/projects/redmine/wiki/Rest_IssueRelations#POST) --> It works.

Could you analyse this issue ?
Thanks

**Comment by NecatiMeral** [comment]
hi @charettemtb,

I'm experiencing the same issue and updated my PR #264.
Let's wait for @zapadi's feedback.
