### ISSUE TITLE
Id of Types is not accesable 

### ISSUE THREAD

**Issue by derek2132** [zapadi/redmine-net-api#268]
-Redmine server version    :3.1.0.stable
-Redmine.Net.Api version  :3.0.6.1
-serialization type (xml or json)  : not used
I want to create new issues by using this library.
But when I tried to coding in the way which is refered in the URL(https://www.redmine.org/projects/redmine/wiki/Rest_api_with_csharp) such as the following , 
there is an error saying that the set method of Id is not visible .

> var newIssue = new Issue { Subject = "test", Project = new IdentifiableName{Id =  1}};

Is there anything wrong ?

Hoping somebody could help .

**Comment by zapadi** [comment]
Hi,

I would recommend to use the latest version of the library (4.0)  and for identifiable names 
```
IdentifiableName.Create<Type>(ID)
```

**Comment by derek2132** [comment]
> Hi,
> 
> I would recommend to use the latest version of the library (4.0) and for identifiable names
> 
> ```
> IdentifiableName.Create<Type>(ID)
> ```
Thank you very much .
Sorry , how can I get the latest vaersion of the DLL?

**Comment by derek2132** [comment]
Thanks you for helping . The latest one works very well.

**Comment by zapadi** [comment]
You are welcome!
