### ISSUE TITLE
Do not add watcher to new Issue

### ISSUE THREAD

**Issue by olegrif** [zapadi/redmine-net-api#272]
Hello!
I create new Issue. I want to add a watcher at once.
The Issue is was created. But I see the watcher is empty.
Why?
My code:
```
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using Redmine.Net.Api;
using Redmine.Net.Api.Types;
using System.Net;

namespace RedmineTest
{
    class Program
    {

        static void Main(string[] args)
        {
            string host = "some host";
            string apiKey = "some api key";
            int id = 0;
            int errorId = 0;
            //System.Net.ServicePointManager.ServerCertificateValidationCallback = ((sender, certificate, chain, sslPolicyErrors) => true);
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; 

            var manager = new RedmineManager(host, apiKey, MimeFormat.Xml, true, null, ServicePointManager.SecurityProtocol);
            var parameters = new NameValueCollection { { "status_id", "*" } };
			
			string documentPath = @"some file";
            byte[] documentData = System.IO.File.ReadAllBytes(documentPath);

            //upload attachment to redmine
            Upload attachment = manager.UploadFile(documentData);

            //set attachment properties
            attachment.FileName = "SomeName.png";
            attachment.Description = "File uploaded using REST API";
            attachment.ContentType = "text/plain";

            //create a list of attachments to be added to issue
            IList<Upload> attachments = new List<Upload>();
            attachments.Add(attachment);

            //Create a issue.
            IdentifiableName name = new IdentifiableName();
            name.Name = "Admin";
            IdentifiableName assigned = new IdentifiableName();
            IdentifiableName tracker = new IdentifiableName();
            tracker.Id = errorId;
            assigned.Name = "some_user";
            assigned.Id = 12;
            var newIssue = new Issue
            {

                StartDate = DateTime.Now,
                Tracker = tracker,
                Subject = "some subject",
                Project = new IdentifiableName { Id = 6 },
                Author = name,
                Description = "Some description",
                Uploads = attachments,
                AssignedTo = assigned,
                Watchers = new List<Watcher>() { new Watcher {Id=8}}
            };
			
			var response=manager.CreateObject(newIssue);
        }
    }
}
```
I am using:
Redmine version - 3.1.14,
Redmine.Net.Api - redmine-net451-api v2.0,
serialization type - json	

Note: when I want to add watcher through AddWatcher function I get message "The page that you trying to update is staled!".

Can you help me with adding watcher to Issue?

**Comment by olegrif** [comment]
My Exception text:
Redmine.Net.Api.Exceptions.ForbiddenException do not handle by user code
  HResult=-2146233088
  Message=Forbidden
  Source=redmine-net451-api
  StackTrace:
       РІ Redmine.Net.Api.Extensions.WebExtensions.HandleWebException(WebException exception, String method, MimeFormat mimeFormat) РІ c:\Users\user\Documents\Visual Studio 2013\Projects\redmine-net-api-master\src\redmine-net40-api\Extensions\WebExtensions.cs:line 72
       РІ Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload(RedmineManager redmineManager, String address, String actionType, String data, String methodName, NameValueCollection parameters) РІ c:\Users\user\Documents\Visual Studio 2013\Projects\redmine-net-api-master\src\redmine-net20-api\Internals\WebApiHelper.cs:line 54
       РІ Redmine.Net.Api.RedmineManager.AddWatcherToIssue(Int32 issueId, Int32 userId) РІ c:\Users\user\Documents\Visual Studio 2013\Projects\redmine-net-api-master\src\redmine-net20-api\RedmineManager.cs:line 282
  InnerException: System.Net.WebException
       HResult=-2146233079
       Message=remote server replyed: (403) Forbidden.
       Source=System
       StackTrace:
            РІ System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
            РІ System.Net.WebClient.UploadString(Uri address, String method, String data)
            РІ System.Net.WebClient.UploadString(String address, String method, String data)
            РІ Redmine.Net.Api.Internals.WebApiHelper.ExecuteUpload(RedmineManager redmineManager, String address, String actionType, String data, String methodName, NameValueCollection parameters) РІ c:\Users\user\Documents\Visual Studio 2013\Projects\redmine-net-api-master\src\redmine-net20-api\Internals\WebApiHelper.cs:line 49
       InnerException:

**Comment by zapadi** [comment]
> 
> 
> Hello!
> I create new Issue. I want to add a watcher at once.
> The Issue is was created. But I see the watcher is empty.
> Why?
> My code:
> 
> ```
> using System;
> using System.Collections.Generic;
> using System.Collections.Specialized;
> using Redmine.Net.Api;
> using Redmine.Net.Api.Types;
> using System.Net;
> 
> namespace RedmineTest
> {
>     class Program
>     {
> 
>         static void Main(string[] args)
>         {
>             string host = "some host";
>             string apiKey = "some api key";
>             int id = 0;
>             int errorId = 0;
>             //System.Net.ServicePointManager.ServerCertificateValidationCallback = ((sender, certificate, chain, sslPolicyErrors) => true);
>             ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; 
> 
>             var manager = new RedmineManager(host, apiKey, MimeFormat.Xml, true, null, ServicePointManager.SecurityProtocol);
>             var parameters = new NameValueCollection { { "status_id", "*" } };
> 			
> 			string documentPath = @"some file";
>             byte[] documentData = System.IO.File.ReadAllBytes(documentPath);
> 
>             //upload attachment to redmine
>             Upload attachment = manager.UploadFile(documentData);
> 
>             //set attachment properties
>             attachment.FileName = "SomeName.png";
>             attachment.Description = "File uploaded using REST API";
>             attachment.ContentType = "text/plain";
> 
>             //create a list of attachments to be added to issue
>             IList<Upload> attachments = new List<Upload>();
>             attachments.Add(attachment);
> 
>             //Create a issue.
>             IdentifiableName name = new IdentifiableName();
>             name.Name = "Admin";
>             IdentifiableName assigned = new IdentifiableName();
>             IdentifiableName tracker = new IdentifiableName();
>             tracker.Id = errorId;
>             assigned.Name = "some_user";
>             assigned.Id = 12;
>             var newIssue = new Issue
>             {
> 
>                 StartDate = DateTime.Now,
>                 Tracker = tracker,
>                 Subject = "some subject",
>                 Project = new IdentifiableName { Id = 6 },
>                 Author = name,
>                 Description = "Some description",
>                 Uploads = attachments,
>                 AssignedTo = assigned,
>                 Watchers = new List<Watcher>() { new Watcher {Id=8}}
>             };
> 			
> 			var response=manager.CreateObject(newIssue);
>         }
>     }
> }
> ```
> 
> I am using:
> Redmine version - 3.1.14,
> Redmine.Net.Api - redmine-net451-api v2.0,
> serialization type - json
> 
> Note: when I want to add watcher through AddWatcher function I get message "The page that you trying to update is staled!".
> 
> Can you help me with adding watcher to Issue?

The watcher id should be a valid id(you'll need to create the watcher before assign it)

**Comment by olegrif** [comment]
The watcher has valid id. I have checked it.

**Comment by olegrif** [comment]
I have decided the problem :-).
1. I create an issue and get it's id.
2. I send to server by plink tool command "python3 addwatcher.py issue_id user_id" there issue_id and user_id are arguments for the script.
3. The script addwatcher.py on Python3 add watcher in the task by redmine-python library.

**Comment by zapadi** [comment]
You can do it in like this:
```
Issue issue = new Issue()
            {
                Subject = "Do not add watcher to new Issue",
                Author = IdentifiableName.Create<IdentifiableName>(1),
                Category = IdentifiableName.Create<IdentifiableName>(1),
                Status = IdentifiableName.Create<IdentifiableName>(1),
                Project = IdentifiableName.Create<IdentifiableName>(1),
                Tracker = IdentifiableName.Create<IdentifiableName>(1),
                Priority = IdentifiableName.Create<IdentifiableName>(1),
                FixedVersion = IdentifiableName.Create<IdentifiableName>(1),
                AssignedTo = IdentifiableName.Create<IdentifiableName>(1),
                ParentIssue = IdentifiableName.Create<IdentifiableName>(1),
                IsPrivate = true,
                EstimatedHours = 10,
                CustomFields = new List<IssueCustomField>()
                {
                    new IssueCustomField()
                    {
                        Multiple = false,
                        Name = "test",
                        Values = new List<CustomFieldValue>()
                        {
                            new CustomFieldValue("cf_custom_field")
                        }
                    }
                },
                Description = "some description",
                Watchers = new List<Watcher>()
                {
                    IdentifiableName.Create<Watcher>(1)
                }
            };
```

Be careful that you need the **Id** of the IdentifiableName and not the **Name** like you can notice in the above example.
