### ISSUE TITLE
Assigning IssueCustomFields to a project should be supported

### ISSUE THREAD

**Issue by peck199** [zapadi/redmine-net-api#277]
The Redmine REST-API allows to assign issue_custom_field_ids to a project at creation-time. 

The .NET API uses the property CustomFields in the project for that purpose, but later for the CustomField-values on project-level. Since the property is internal-set only, I need to use reflection to assign the desired list, which works quite well but should not be considered a valid solution. Since the IssueCustomFields can only be assigned at creation-time, I'd suggest to have a Project-constructor which accepts a list of IssueCustomFields and assigns them. Since they cannot be read, an extra property makes no sense, but maybe a private field different to CustomFields, which is used for a different purpose as well.

**Comment by zapadi** [comment]
Hello,

The issue is fixed and the package is available on nuget.
