### ISSUE TITLE
Web-exception handling: 502 (Bad Gateway) not handled

### ISSUE THREAD

**Issue by peck199** [zapadi/redmine-net-api#278]
When retrieving objects I receive a 502 error (because I broke my redmine). But the error is not handled as a web exception, so GetObjects just returns null instead of throwing an exception.

IMHO, In the method HandleWebException of the class WebExceptionExtensions, the switch-block over the StatusCode should handle the default-case (only the switch-block above does).

**Comment by zapadi** [comment]
I've published a new version that handles the issue described.
