### ISSUE TITLE
Setting a custom field value when creating an issue doesn't work.

### ISSUE THREAD

**Issue by KoertLichtendonk** [zapadi/redmine-net-api#283]
I am having an issue with creating Redmine issues where I want the values of custom fields to be set. The issue is created but the values of the custom fields are not set.

The Redmine version I am using is 3.4.4.stable.
The Redmine.Net.Api version I am using is 4.2.0, I've tried going to a newer version and to older versions with the same outcome.
I am using the Json serialization, although I've also used the Xml serialization before which didn't work either.

```
            if (issue == null)
            {
                issue = new Issue();
            }

            issue.Subject = subject;
            issue.ParentIssue = parent;

            if (issue.ParentIssue != null)
            {
                var parameters = new NameValueCollection { { "issue_id", parent.Id.ToString() } };
                List<Issue> parentIssuesObjects = Redmine._rm.GetObjects<Issue>(parameters);
                Issue parentIssue = parentIssuesObjects[0];

                issue.Project = parentIssue.Project;
                issue.Tracker = parentIssue.Tracker;
            }

            issue.CustomFields = new List<IssueCustomField>();
            issue.CustomFields.Add(new IssueCustomField() { Name = "Klantnaam", Values = new List<CustomFieldValue> { new CustomFieldValue(Klantnaam) } }); 

            Issue tempIssue = Redmine._rm.CreateObject(issue);
```

Does anyone have any idea what I'm doing wrong here? The variable Klantnaam is a string.

**Comment by zapadi** [comment]
Hi,
If you want to set or change the custom fields value you need the **id**(the custom field should exists) of the respective custom fields. The custom field **Name** is not required.

**Comment by KoertLichtendonk** [comment]
> 
> 
> Hi,
> If you want to set or change the custom fields value you need the **id**(the custom field should exists) of the respective custom fields. The custom field **Name** is not required.

I thought so but I can't change the value of the Id property, so how do I change the Id of the IssueCustomField?
`The property or indexer 'Identifiable<IdentifiableName>.Id' cannot be used in this context because the set accessor is inaccessible`

This is how I would imagine it.
`issue.CustomFields.Add(new IssueCustomField() { Id = 45, Values = new List<CustomFieldValue> { new CustomFieldValue(Klantnaam) } }); `

**Comment by zapadi** [comment]
RedmineApi version >= 4.0

```
issue.CustomFields.Add( (IssueCustomField) IdentifiableName.Create(45) { Values = new List<CustomFieldValue> { new CustomFieldValue(Klantnaam) } }); 

```
