### ISSUE TITLE
Issue Relations Read Error for Copied Issues (Relation Type : copied_to)

### ISSUE THREAD

**Issue by ferhatbulut** [zapadi/redmine-net-api#288]
Dears,

When reading the issue using .NET API 4.2.3; on **ReadJson** method in **Redmine.Net.Api.Types.IssueRelation**,
If the Related Issue is created using Copy feature, then Relation Type is coming as "copied_to".
But there is no copied_to type in **IssueRelationType** Enum then SDK throws an error.
When I added **Copied_To** enum type in **IssueRelationType** object, then the problem is solved.

Redmine Server Version : Unknown (Sorry, Remote Redmine we are using)
Redmine.Net.Api Version : 4.2.3
SerializationType : JSON

- Create an Issue A
- Create an Issue B using Copy To operation
- Issue B will be listed under Relations of Issue A
- Try to GetIssue for Issue A using includes:relations
- Throws an error "copied_to was not found."

Solution
- Add Copied_To in IssueRelationType Enum Class

"relations": [
{
"id": 2722,
"issue_id": 16767,
"issue_to_id": 17576,
"relation_type": "relates",
"delay": null
},
{
"id": 2921,
"issue_id": 16767,
"issue_to_id": 17571,
"relation_type": "relates",
"delay": null
},
{
**"id": 2215,
"issue_id": 15557,
"issue_to_id": 16767,
"relation_type": "copied_to",
"delay": null**
}
],

Bold item can not be deserialized from JSON because of undefined relation type.

Best regards

**Comment by zapadi** [comment]
Thank you for pointing this out.
