### ISSUE TITLE
Creation of private Projects not possible

### ISSUE THREAD

**Issue by NecatiMeral** [zapadi/redmine-net-api#290]
Hi,

when creating a project and setting the `IsPrivate` property to `false`, the project is created as a public project anyway.
I've tracked down the root cause to the usage of `WriteIfNotDefaultOrNull` when serializing boolean values.

I'll commit a PR which fixes this issue.

## Questions
- Which Redmine server version are you using: 4.1.2.stable
- Which Redmine.Net.Api version are you using: 4.2.3
- Which serialization type (xml or json) are you using: json
- ~A list of steps or a gist or a github repository which can be easily used to reproduce your case.~

**Comment by zapadi** [comment]
Thanks
