### ISSUE TITLE
GetObjects Include Watchers

### ISSUE THREAD

**Issue by KoertLichtendonk** [zapadi/redmine-net-api#300]
I just found out that we can include some of the missing data when retreiving issues so I wanted to include all watchers. When including watchers to GetObjects the watchers property remains null. When including it to GetObject it works fine. Is this a bug or is this simply not supported (yet) for GetObjects?

I am on Redmine version 4.2.0.stable and using Redmine.Net.Api version 4.2.0.

This is what I use for retreiving the issues:
```
                _AllIssues = new Dictionary<string, Issue>();

                NameValueCollection parameters = new NameValueCollection {
                    { "status_id", "1|13|2|12|4|10" }
                    , { RedmineKeys.INCLUDE, RedmineKeys.WATCHERS }
                };

                foreach (var Issue in Redmine._rm.GetObjects<Issue>(parameters))
                {
                    _AllIssues.Add(String.Format("#{0}: {1}", Issue.Id, Issue.Subject), Issue);
                }
```

**Comment by zapadi** [comment]
Hi,
Only  attachments - Since 3.4.0 & relations can be retrieve for issues (GetObjects).
