### ISSUE TITLE
Project Memberships only access one of two routes

### ISSUE THREAD

**Issue by zipacna** [zapadi/redmine-net-api#304]
Hello,

first up, good tool, worked for most of my use cases (so far). The only (micro) use case I had to write simple DTOs for, is "Getting Memberships by Project"; as it seems redmine-net-api is only handling the `memberships` route not the `project/<id>/memberships` route, see [Relevant Redmine Docs](https://www.redmine.org/projects/redmine/wiki/Rest_Memberships).

Am I looking at the wrong Type within the redmine-net-api? Is it only a matter of getting the right NameValueCollection?

- Which Redmine server version are you using: **4.0.3.stable** (with Easy Redmine 2019 Platform 07.05)
- Which Redmine.Net.Api version are you using: **4.3.0 redmine-api-signed** (latest on nuget tab of vs2022 .NET Core API 3.1)
- Which serialization type (xml or json) are you using: **JSON**
- A list of steps or a gist or a github repository which can be easily used to reproduce your case: **see below**

Naive Approach
````csharp
// NameValueCollection is always a big guessing game for me.
var parameters = new NameValueCollection { { RedmineKeys.MEMBERSHIPS, RedmineKeys.ALL } };
_redmineManager.GetObject<ProjectMembership>(_config.GetValue<string>("PMS:ProjectId"), parameters);
````

Simple DTOs
````csharp
// Call of System.Text.Json
JsonSerializer.Deserialize<ProjectWrapper>(responseBody);

// DTOs
public class ProjectWrapper
{
    [JsonPropertyName("memberships")]
    public List<MembershipWrapper> Memberships { get; set; }

    [JsonPropertyName("total_count")]
    public int TotalCount { get; set; }

    [JsonPropertyName("offset")]
    public int Offset { get; set; }

    [JsonPropertyName("limit")]
    public int Limit { get; set; }
}

public class MembershipWrapper
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("project")]
    public IdNameWrapper Project { get; set; }

    [JsonPropertyName("user")]
    public IdNameWrapper User { get; set; }

    [JsonPropertyName("roles")]
    public List<IdNameWrapper> Roles { get; set; }
}

public class IdNameWrapper
{
    [JsonPropertyName("id")]
    public int Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("inherited")]
    public bool Inherited { get; set; }
}
````

Little semi-related side question: When querying the following, shouldn't I get back a list of all Issues (with relations and journals)? When browsing manually I get roughly 17k results in the redmine instance I am using, but by API I only get like 55. Is it a pagination or permission issue (logged in with the user of the api key)?
````csharp
var params = new NameValueCollection { { RedmineKeys.STATUS_ID, RedmineKeys.ALL }, { RedmineKeys.INCLUDE, RedmineKeys.RELATIONS }, { RedmineKeys.INCLUDE, RedmineKeys.JOURNALS } };
_redmineManager.GetObjects<Issue>(params);
````

**Comment by zapadi** [comment]
Hello,
Sorry for such a late answer
The second route for (project) memberships will be available next week.
If you need/want to load multiple associations you can do it like this:
```
var params = new NameValueCollection { { RedmineKeys.STATUS_ID, RedmineKeys.ALL }, **{ RedmineKeys.INCLUDE, $"{RedmineKeys.RELATIONS }, {RedmineKeys.JOURNALS}" }** };
_redmineManager.GetObjects<Issue>(params);
```
