### ISSUE TITLE
Can not create Issue with ParentIssue

### ISSUE THREAD

**Issue by jpkempkes** [zapadi/redmine-net-api#306]
Hi, 

could you provide a short example, how to create an Issue with a parent issue in Version 4.3.0? 

Taking an existing Issue from a pre-loaded list, shows that Issue does not cast to IdentifiableName
```
            Issue? newIssue = new Issue()
            {
                Subject = "test with internal tasks2",
                Project = projects.Where(pr => pr.Name == "Team").Single(),
                Tracker = trackers.Where(t => t.Name == "Internal Tasks").Single(),
                ParentIssue = issues.Where(i => i.Id == 12345).Single()
        };
```
--> 

Error	CS0029	Cannot implicitly convert type 'Redmine.Net.Api.Types.Issue' to 'Redmine.Net.Api.Types.IdentifiableName'	

Creating an IdentifiableName does not work, as one can only set the Name (ID is private and not supported by the Constructor)

```
newIssue.ParentIssue = new IdentifiableName();
newIssue.ParentIssue.Name = "12345";
```

and setting the ID into the name fails. 

So, how to set the ParentIssue correctly?

I think either adding the cast or making IdentifiableName.ID setter public would be sufficient? 

Thanks for your help

**Comment by jpkempkes** [comment]
Well, Create is a generic and does not have an appropriate conversion

`  var parentId = IdentifiableName.Create(12345);`

--> The type arguments for method 'IdentifiableName.Create<T>(int)' cannot be inferred from the usage. Try specifying the type 


and 
` var parentId = IdentifiableName.Create<Issue>(12345);`

--> The type 'Redmine.Net.Api.Types.Issue' cannot be used as type parameter 'T' in the generic type or method 'IdentifiableName.Create<T>(int)'. There is no implicit reference conversion from 'Redmine.Net.Api.Types.Issue' to 'Redmine.Net.Api.Types.IdentifiableName'.	



I have changed

`public sealed class Issue : Identifiable<Issue>, ICloneable`

to 

`public sealed class Issue : IdentifiableName, ICloneable, IEquatable<Issue>`
(and removed the overload from Equals)

which does the trick for me.

**Comment by jpkempkes** [comment]
Btw, I really appreciate your timely answer. That is impressive.

**Comment by zapadi** [comment]
The previous answer is missing the code formatter.  
*IdentifiableName.Create(12345)* would became **`IdentifiableName.Create<IdentifiableName>(12345)`**

**Comment by jpkempkes** [comment]
Thanks! works

`      Issue? newIssue = new Issue()
            {
                Subject = "test with internal tasks2",
                Project = projects.Where(pr => pr.Name == "Team").Single(),
                Tracker = trackers.Where(t => t.Name == "Internal Tasks").Single(),
                ParentIssue = IdentifiableName.Create<IdentifiableName>(48385) 
        };`

**Comment by zapadi** [comment]
> Btw, I really appreciate your timely answer. That is impressive.

Thanks

**Comment by zapadi** [comment]
> Thanks! works
> 
> ```
>             {
>                 Subject = "test with internal tasks2",
>                 Project = projects.Where(pr => pr.Name == "Team").Single(),
>                 Tracker = trackers.Where(t => t.Name == "Internal Tasks").Single(),
>                 ParentIssue = IdentifiableName.Create<IdentifiableName>(48385) 
>         };```
> ```

Glad to hear that is working well
