### ISSUE TITLE
Debug into source code

### ISSUE THREAD

**Issue by Menci77** [zapadi/redmine-net-api#308]
Hi I need some help/information, I am using the redmine api nuget package( https://www.nuget.org/packages/redmine-api) in my application, and I am trying to debug into the api's code, but can't seem to be able to do it. 
I tried several steps I found on how to debug into nuget package code (uncheck the Enable just my code, check the Enable source link support etc.), but it just can't seem to load the symbols for this package. 
I am using Visual Studio 2022 (17.1.1).

Can you give me some insight on this matter? Any help would be appreciated!

-  Redmine server version:  5.0.3.stable
- Redmine.Net.Api version: 4.3.0

P.s. I don't know if it means anything, but in the nuget package explorer I see this:
![image](https://user-images.githubusercontent.com/61515787/196972152-2e0fb77f-6b32-4ef0-92c7-5cc2bfd6abb3.png)

**Comment by zapadi** [comment]
Fixed in 4.6.9 version
