### ISSUE TITLE
Now create new Project Membership

### ISSUE THREAD

**Issue by smap9** [zapadi/redmine-net-api#310]
refs #170

I want to create new Project membership.

```
var membership = new Redmine.Net.Api.Types.ProjectMembership();
membership.Project = IdentifiableName.Create<IdentifiableName>(1);
```

But the Project is a protected member 

https://github.com/zapadi/redmine-net-api/blob/master/src/redmine-net-api/Types/ProjectMembership.cs#L46

How can I create a new project membership?

**Comment by zapadi** [comment]
I'm afraid that you have to go through the project to create a new project membership

**Comment by smap9** [comment]
@zapadi I'm sorry but I don't know how this helps.

When I load a project
```c#
var project = redmineManager.GetObject<Project>(projectId.Id.ToString(), null);
```
I get a object of https://github.com/zapadi/redmine-net-api/blob/master/src/redmine-net-api/Types/Project.cs. But there is no possibility to add a membership.
