### ISSUE TITLE
Problem of type on ChangeSet Revision property

### ISSUE THREAD

**Issue by gwenael-louandre** [zapadi/redmine-net-api#311]
Hello,
I'm trying to get changesets from an issue. I just saw that revision property is always set to 0. In fact, the revision type in the C# class is int whereas  it should be a string.
![image](https://user-images.githubusercontent.com/4600171/203157050-94c5ed19-0741-4794-bd17-29733d9bbbda.png)

Here is an example : 
- Data from XML API
![image](https://user-images.githubusercontent.com/4600171/203156934-2174e510-558a-4fa5-8ed2-e93751dc285d.png)
- Data in C#
![image](https://user-images.githubusercontent.com/4600171/203156991-5980af33-91b6-4dad-81f4-4a99668f187d.png)

Is there something I don't understand in the working or is there an issue on type?

I use the 4.3.0 version.

Thanks.

**Comment by gwenael-louandre** [comment]
Thanks for the correction. Do you have an idea for the new version availability?

**Comment by zapadi** [comment]
You are welcome. It will be available today.
