### ISSUE TITLE
Compatibility with Easy Redmine 12.5.3 / API 3.7.7

### ISSUE THREAD

**Issue by mkacena** [zapadi/redmine-net-api#320]
We were using this library to integrate our app to Easy Redmine. After a recent upgrade of the cloud Easy Redmine to version 12.5.3, the library stopped working and is throwing errors. I would like to ask what versions of Redmine and its API are supported and if there is a recommended way to integrate to the newest version.

Redmine version: 12.5.3
Redmine API version: 3.7.7
redmine-api NuGet version: 4.6.0
Serialization type: XML

This simple code which was working before throws error now:

```
RedmineManager manager;
manager = new RedmineManager(host, login, password);
return manager.GetCurrentUser();
```

Error:

Message: 
Test method XXX.EasyRedmine.Api.Tests.NetRedmineIssuesProcessorTests.SignInTest threw exception: 
Redmine.Net.Api.Exceptions.RedmineException: There is an error in XML document (1, 82121). ---> System.InvalidOperationException: There is an error in XML document (1, 82121). ---> System.InvalidOperationException: There is an error in XML document (1, 241). ---> System.InvalidOperationException: There is an error in XML document (1, 39). ---> System.InvalidOperationException: <name xmlns=''> was not expected.

  Stack Trace: 
XmlSerializationReaderMembershipRole.Read1_role()
 --- End of inner exception stack trace ---
XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
XmlReaderExtensions.ReadElementContentAsCollection[T](XmlReader reader)
Membership.ReadXml(XmlReader reader)
XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
XmlSerializationReaderMembership.Read1_membership()
 --- End of inner exception stack trace ---
XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
XmlReaderExtensions.ReadElementContentAsCollection[T](XmlReader reader)
User.ReadXml(XmlReader reader)
XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
XmlSerializationReaderUser.Read1_user()
 --- End of inner exception stack trace ---
XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
XmlRedmineSerializer.XmlDeserializeEntity[TOut](String xml)
XmlRedmineSerializer.Deserialize[T](String response)
 --- End of inner exception stack trace ---
XmlRedmineSerializer.Deserialize[T](String response)
WebApiHelper.ExecuteDownload[T](RedmineManager redmineManager, String address, NameValueCollection parameters)
NetRedmineIssuesProcessor.SignIn(String host, String login, String password) line 147
NetRedmineIssuesProcessorTests.SignInTest() line 28

**Comment by zapadi** [comment]
As I see it, this appears to be more of an issue related to Easy Redmine.
