### ISSUE TITLE
How to get x issues?

### ISSUE THREAD

**Issue by xavierdono** [zapadi/redmine-net-api#325]
Hello,

I try to get 2 issues by id but I get all issues?
Which parameters I need to use? I try ID, ISSUES, ISSUE, ISSUE_ID.

`
var parameters = new NameValueCollection
{
    { RedmineKeys.ISSUE_ID, "1" }
  , { RedmineKeys.ISSUE_ID, "2" }
};

foreach (var issue in manager.GetObjects<Issue>(parameters))
{
  Console.WriteLine($"{issue.AssignedTo?.Name} - {issue.Status.Name} - {issue.FixedVersion?.Name} - {issue.Subject}");
}
`

BR,
Xavier

**Comment by zapadi** [comment]
Hi, 
You can do it like this:
```
var ids = new ["1", "2"];

foreach(var id in ids)
{
var parameters = new NameValueCollection {{ RedmineKeys.ISSUE_ID, id }};

foreach (var issue in manager.GetObjects(parameters))
{
        Console.WriteLine($"{issue.AssignedTo?.Name} - {issue.Status.Name} - {issue.FixedVersion?.Name} - {issue.Subject}");
}
}
```
You can create an extension to help you with.
