### ISSUE TITLE
Remove internal setter from Notes from Journals

### ISSUE THREAD

**Issue by Fizo55** [zapadi/redmine-net-api#334]
https://python-redmine.com/resources/issue.html#journals

As you can see there, you should be able to update the notes from journals, whilst it's not possible now because the setter from Journal class is set as Internal which shouldn't be the case.

There is only 1 element we can update in journal and it's the Notes, it shouldn't be internal,

Putting an empty string to Journal's notes will delete the journal.

**Comment by zapadi** [comment]
Jurnal update will be available in the next version

**Comment by Fizo55** [comment]
> Jurnal update will be available in the next version

Any ETA of the next version, when do you think it will be released ?

**Comment by zapadi** [comment]
By the end of the month

**Comment by Fizo55** [comment]
> By the end of the month

Any ETA now ?

**Comment by zapadi** [comment]
Version 4.6.3 deployed
