### ISSUE TITLE
Journal issue

### ISSUE THREAD

**Issue by Fizo55** [zapadi/redmine-net-api#337]
With the new update, I did that in order to upgrade my journal :

                if (issue.Journals != null)
                {
                    foreach (var journal in issue.Journals.Where(s => !string.IsNullOrEmpty(s.Notes)).ToList())
                    {
                        _logger.Information(journal.Notes);
                        journal.Notes = string.Empty;
                        _logger.Information(journal.Notes);
                    }
                    _manager.UpdateObject(issue.Id.ToString(), issue);
                }
                
  My first logging will display "test3" which is my note, I'll then set it to string.Empty which mean I want to delete it, then I'm making just making sure it got set to null to my second logger ain't logging anything.
  
  I'm then updating my issue but my note ain't getting deleted, am I doing something wrong ?

**Comment by zapadi** [comment]
What version of .NET & Redmine are you using?

**Comment by Fizo55** [comment]
> What version of .NET & Redmine are you using?

NET 7 and Redmine 4.1.1

**Comment by zapadi** [comment]
Could you tell me if the journal that you want to delete has no value set for 'details' field?

**Comment by Fizo55** [comment]
> Could you tell me if the journal that you want to delete has no value set for 'details' field?

I just debugged it, the 'details' field is null

**Comment by zapadi** [comment]
Updating journal notes via REST API is available starting from Redmine version 5.0.0 onwards

**Comment by Fizo55** [comment]
> Updating journal notes via REST API is available starting from Redmine version 5.0.0 onwards

Oh, thanks
