### ISSUE TITLE
using Excel with redmine-net-api to edit custom field

### ISSUE THREAD

**Issue by ashrafalzyoud** [zapadi/redmine-net-api#359]
Since you’re using Windows and Excel, the C# library (redmine-net-api) is a great choice for ease of integration with Windows and handling updates in Redmine. Here’s why:

Excel and .NET Compatibility: C# can read data directly from Excel, making it easy to retrieve issue IDs and custom field values and update them in Redmine.
Native Windows Support: With Visual Studio, you have a straightforward way to build and run C# applications on Windows.
Easy Bulk Processing: You can use the .NET library to loop through rows in Excel and update each issue in Redmine with the corresponding custom field value.
Here’s a step-by-step guide for reading an Excel file and updating Redmine issues using the redmine-net-api library.

Step 1: Set Up Your Environment
Install Visual Studio (if you don’t already have it).

Install the Redmine .NET API Library:

Open Visual Studio.
Go to Tools > NuGet Package Manager > Manage NuGet Packages for Solution.
Search for Redmine.Net.Api and install it.
Install ExcelDataReader Library (for reading Excel files):

Similarly, install ExcelDataReader and ExcelDataReader.DataSet packages via NuGet. These libraries allow easy reading of Excel files in C#.
Step 2: Prepare Your Excel File
Create an Excel file (e.g., UpdateIssues.xlsx) with two columns:
IssueID (Column A): Contains the issue IDs.
CustomField10 (Column B): Contains the new values for Custom Field 10.
Save it in a location you can reference in your code.
Step 3: Write the C# Code
The following code reads the Excel file, retrieves each issue ID and custom field value, and updates the issues in Redmine.

csharp
Copy code
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using Redmine.Net.Api;
using Redmine.Net.Api.Types;
using ExcelDataReader;

class Program
{
    static void Main()
    {
        // Redmine server details
        string host = "http://your-redmine-server.local";
        string apiKey = "your_api_key";
        var redmineManager = new RedmineManager(host, apiKey);

        // Path to Excel file
        string filePath = @"C:\path\to\UpdateIssues.xlsx";

        // Load Excel data
        var issuesToUpdate = LoadIssueData(filePath);

        // Update each issue in Redmine
        foreach (var issueData in issuesToUpdate)
        {
            var issueId = issueData.Key;
            var customFieldValue = issueData.Value;

            // Fetch and update the issue
            var issue = redmineManager.GetObject<Issue>(issueId.ToString(), null);
            var customField = issue.CustomFields.Find(cf => cf.Id == 10);
            if (customField != null)
            {
                customField.Value = customFieldValue;
                redmineManager.UpdateObject(issue.Id.ToString(), issue);
                Console.WriteLine($"Updated issue ID {issueId} with value: {customFieldValue}");
            }
            else
            {
                Console.WriteLine($"Custom Field 10 not found for issue ID {issueId}");
            }
        }
    }

    // Method to load Excel data
    static Dictionary<int, string> LoadIssueData(string filePath)
    {
        var issues = new Dictionary<int, string>();

        using (var stream = File.Open(filePath, FileMode.Open, FileAccess.Read))
        {
            using (var reader = ExcelReaderFactory.CreateReader(stream))
            {
                var result = reader.AsDataSet();
                var table = result.Tables[0];

                // Skip header row and read IssueID and CustomField10 values
                for (int i = 1; i < table.Rows.Count; i++)
                {
                    int issueId = int.Parse(table.Rows[i][0].ToString());
                    string customField10Value = table.Rows[i][1].ToString();
                    issues[issueId] = customField10Value;
                }
            }
        }
        return issues;
    }
}
Explanation of the Code
LoadIssueData: This method reads the Excel file and extracts issue IDs and corresponding custom field values into a dictionary.
API Call: For each issue ID in the Excel file, the script:
Fetches the issue using GetObject.
Locates Custom Field 10 and updates it with the new value.
Calls UpdateObject to save changes to Redmine.
Running the Script
Update host, apiKey, and the filePath to match your Redmine server and Excel file location.
Run the program from Visual Studio.
Monitor the console output for updates or errors.
This solution leverages both Excel for data input and .NET for smooth Redmine API interactions, making it ideal for your setup on Windows. Let me know if you need help with any part of this process!

**Comment by ashrafalzyoud** [comment]
can i do these steps to update my issues as example (custom_field_10) bec i have (10000) issues need update
can from excel read issu_id and the value of cf_10
@tobster-de 
@wizicer 
@Elvaron 
@ANovitsky

**Comment by zapadi** [comment]
Is this an issue?

**Comment by ashrafalzyoud** [comment]
Yes can I do these steps

**Comment by zapadi** [comment]
I don't understand why this is an issue of this API and what tries to solve
