### ISSUE TITLE
NuGet version update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zapadi/redmine-net-api#87]
```
NuGet Package is ver 0.10 and not 0.11 despite the fact that the package ver 
0.11 has been released quite a few weeks ago. 
As the NuGet package redirects to this page I hope it's a good place to open 
this issue.
```

Original issue reported on code.google.com by `dawid.sz...@gmail.com` on 2 Feb 2015 at 10:21

**Comment by Razzeee** [comment]
@zapadi 
This would be great as the version in nuget is 2 years old and the new one fixes a pretty annoying warning.

**Comment by zapadi** [comment]
I'll take care of it asap.

**Comment by zapadi** [comment]
redmine-api 0.13.0

**Comment by Razzeee** [comment]
Thank you!

**Comment by zapadi** [comment]
you're welcome.
