### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Whitebeard86** [zapadi/redmine-net-api#90]
Hello,

Where can I find documentation related to this project ? 
If you can provide an address with examples I appreciate..

Thanks.

**Comment by zapadi** [comment]
Hi,

I'll update the wikis in weekend.

Adrian Popescu

On 24 Apr 2015, at 11:48, João Alves <notifications@github.com> wrote:

Hello,

Where can I find documentation related to this project ?
If you can provide an address with examples I appreciate..

Thanks.

—
Reply to this email directly or view it on GitHub
<https://github.com/zapadi/redmine-net-api/issues/90>.

**Comment by Whitebeard86** [comment]
Thank you :)
