### ISSUE TITLE
work with attachment

### ISSUE THREAD

**Issue by a2exey** [zapadi/redmine-net-api#95]
Hello! Please provide example with upload attachment to redmine.

**Comment by zapadi** [comment]
namespace RedmineTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string host = "";
            string apiKey = "";
            string projectId = "1";
            var manager = new RedmineManager(host, apiKey);

            var project = manager.GetObject<Project>(projectId , null);
           
            //read document from specified path
            string documentPath = "documentLocalPath";
            byte[] documentData = File.ReadAllBytes(documentPath);
            //upload attachment to redmine
            Upload attachment = manager.UploadFile(documentData);

            //set attachment properties
            attachment.FileName = "AttachmentUploaded.txt";
            attachment.Description = "File uploaded using REST API";
            attachment.ContentType = "text/plain";

            //create list of attachments to be added to issue
            IList<Upload> attachments = new List<Upload>();
            attachments.Add(attachment);

            //create issue and attach document
            Issue issueWithAttachment = manager.CreateObject<Issue>(
                                            new Issue 
                                            {
                                                Project = project,
                                                Subject = "Issue with attachment",
                                                Uploads = attachments
                                            });
        }
    }
}
