### ISSUE TITLE
Attachments null

### ISSUE THREAD

**Issue by Whitebeard86** [zapadi/redmine-net-api#96]
Hello,

Currently I'm having an issue with the library, when I try to grab all issues the attachments are always set to null. I'm doing something wrong?

            var parameters = new NameValueCollection();
            parameters.Add("project_id", project);        
            parameters.Add("status_id", "*");

            foreach (var issue in manager.GetTotalObjectList<Issue>(parameters))
            {
               ....
            }

**Comment by Whitebeard86** [comment]
I've seen that this is a limitation from the API, it worked when I fetch a singular issue.

Another problem now, how can I delete an attachment from an Issue?

Thanks.

**Comment by ANovitsky** [comment]
Redmine API doesn't support the removal of attachments. http://www.redmine.org/projects/redmine/wiki/Rest_api#Attaching-files
http://www.redmine.org/projects/redmine/wiki/Rest_Attachments
